### ISSUE TITLE
We should render realtime PDF's as vectorised PDF not rasterised

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#10]
# Problem

When we get a report from Realtime we cannot cut and paste text from it. This is inconvenient and leaves one vulnerable to copy & paste errors.

# Expected Behaviour

If possible it would be nice to have the PDF's rendered as vectorised. The map would still be an image but the tables etc would be text that can be copy & pasted.

Environment
Proposed Solution

@lucernae to investigate setting composer to vector mode not raster mode before rendering. @Gustry provide support if needed.

See original ticket at https://github.com/inasafe/inasafe/issues/2736 for further discussion.

**Comment by Charlotte-Morgan** [comment]
Hi @myarjunar , @Gustry @ivanbusthomi - is this still relevant with the new version 4 templates?

**Comment by lucernae** [comment]
I will ask @myarjunar about this possibility.

**Comment by Gustry** [comment]
The composer in QGIS 3 is coming with vectorized PDF! ;-)

**Comment by lucernae** [comment]
Done!
