### ISSUE TITLE
Prepare to migrate backup architecture to be able to use by Rancher

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#101]
Our current backup system relies on accessing the host machine directly and doing several commands to fetch or push backup.
We need to be able to support this from rancher, minimally, using shell login.

ref #91

**Comment by gubuntu** [comment]
@lucernae did you do this yet for BNPB Rancher setup?

**Comment by gubuntu** [comment]
This issue was moved to inasafe/docker-realtime-orchestration#73
