### ISSUE TITLE
Provide sysadmin documentation for training

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#102]
We need to provide sysadmin documentation 

- [x] Management commands/instructions for certain tasks
- [x] Setting up Rancher server and agents
- [x] Setting up shared storage infrastructure
- [x] Setting up backup and disaster recovery handling

**Comment by gubuntu** [comment]
@lucernae please add the link(s) to the docs and extend the existing docs to describe what happens when there are new commits and how to deploy upgrades

**Comment by lucernae** [comment]
I merged the documentation to our Training Preparation Course GDrive
