### ISSUE TITLE
Staging InaSAFE Realtime Volcanic Ash is not generating report

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#104]
### Problem 
Last week Ibu @estukriswati has tried uploading a volcanic ash data to the staging site, but the report won't generate even though the data uploaded already listed.

I already checked the data, and make sure that there is no issue in the coordinate system.

### Expected Behaviour
It should generate the report when the input data is correct.

---
**CC** : @gubuntu @Charlotte-Morgan @lucernae @akbargumbira

**Comment by lucernae** [comment]
Hi, the problem is coming from the regression from changes in GeoSAFE.
GeoSAFE uses direct file access now, while InaSAFE Django still uses URL.
I fixed the problem but InaSAFE Django still uses URL to pass data.
@ivanbusthomi can you close this after testing it again (I already tested it myself).

**Comment by ivanbusthomi** [comment]
HI @lucernae , I already test it and it is working great! thanks for the fix
