### ISSUE TITLE
Earthquake distance is not showing the correct distance

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#108]
When I am looking at the realtime earthquake result, I found that the distance is not quite make sense
![image](https://user-images.githubusercontent.com/7351977/29698560-8c437b3a-8980-11e7-8697-55d2e42078e8.png)

 I am guessing that the caused of this is because the coordinate of the epicenter and the nearest city are in WGS84 coordinate system that has decimal degree unit. So the distance calculated are not actually in metric kilometer unit, but in a lat/long decimal degree unit. In order to get the distance in metric, I think we need to reproject it or use a rough estimation of 1 lat/long degree that is equal roughly to 111km.

Beside that, seeing the function to calculate the distance in here, 
https://github.com/inasafe/inasafe-realtime/blob/bae2cb309396dbd1493261a93bfe4262ecd098b1/src/realtime/earthquake/shake_event.py#L594
Correct me if I am wrong, but I think the sqrDist returns a squared distance between two points, so i think it needs to be rooted to get the actual distance.

Using above case as an example, asuming the distance is still squared and in lat/long unit, we can do the rough calculation as follow:
```
latlong_squared_distance = 0.49
latlong_distance = (0.49)^(0.5)
                 = 0.7
metric_distance = 0.7 * 111 km
                = 77.69999 km
```
I tried checking the distance by doing manual measurement in QGIS, the result are close to the rough calculation. 
![image](https://user-images.githubusercontent.com/7351977/29699187-efcfb76e-8984-11e7-955d-eb426e12033f.png)

---

**CC** : @lucernae @gubuntu @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
Good bug catching @ivanbusthomi . I think you need to check with @timlinux on this one. I think he wrote that part of the code.

**Comment by gubuntu** [comment]
rather use geodjango or QGIS spheroid distance calculation

**Comment by lucernae** [comment]
@ismailsunni @myarjunar can you comment on this one? I think this also needs to be done on InaSAFE side.

**Comment by ismailsunni** [comment]
Hi @lucernae 
IIRC, @ivanbusthomi has made a post processor to get the distance from cities. Perhaps it's already done. Let's ask him.

**Comment by gubuntu** [comment]
status @ivanbusthomi ?

**Comment by ivanbusthomi** [comment]
Hi @gubuntu This will be fixed in the v4 of InaSAFE realtime.
