### ISSUE TITLE
Leaflet map in flood realtime should use same colour scheme as PetaJakarta

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#12]
Problem

Having a different colour scheme for the flood realtime is confusing. We should follow the PetaJakarta scheme. Also we should make a legend for the map.
Expected Behaviour

    Colours are consistent with PetaJakarta
    A legend on the map explains the colours

Environment
Proposed Solution

Take a look at how I made this legend here: http://kartoza.com/wms-legend-plugin-for-leaflet/ and implement something similar (but just with a static image for the legend).

See original ticket at https://github.com/inasafe/inasafe/issues/2739 for further discussion.

**Comment by lucernae** [comment]
duplicate of #48
