### ISSUE TITLE
obtain and process missing shakemaps

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-realtime#121]
There are several gaps in the data, made obvious when doing time-series visualisations.

Send Pak Yedi and Pak Hartadi at BMKG a list of shakemap ids to show whe we have and request that they send any missing ones

related to #94

**Comment by samnawi** [comment]
My apologies, I just see this ticket and realized if it was assigned to me.

**Comment by gubuntu** [comment]
status @samnawi ?

**Comment by lucernae** [comment]
Partially able to get the data.
