### ISSUE TITLE
User account for ash on staging

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#126]
BNPB and PDC are requesting access to InaSAFE Realtime Ash on staging.

DMI are happy for them to have user access (but not admin rights) 
Could you please create a user access account we can share  to any non admin users until we migrate the system to production?

**Comment by gubuntu** [comment]
@lucernae can we use the existing 'test ash user' and just remove admin status?

**Comment by lucernae** [comment]
Just for confirmation, 'Ash user' were given access to just the admin page related with Ash only, like the Ash Reports and Volcanoes List. This is useful for example if Ash Users wanted to add/change volcanoes or delete existing Ash Analysis. They were not given access to the whole admin privilege.
Is this ok or should I hide the admin page for this kind of user?

**Comment by Charlotte-Morgan** [comment]
@lucernae - I think Ash User will only need access to Volcanic Ash admin.

**Comment by gubuntu** [comment]
After #127, which is due this week, BNPB and PDC will have access to Ash as it will be public, which will make this issue redundant.

**Comment by gubuntu** [comment]
we will set up the same account on production as exists on staging once ash goes live.
