### ISSUE TITLE
Migrate Ash Realtime to production

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#127]
DMI and PVMBG would like to share ash realtime reports through production.

Steps to support this:
- [x] prepare everything on staging
- [x] prepare about text for ash and upload to content management system #142
- [x] advise PVMBG that its ready
- [x] push the activate button

This will still rely on manual hazard data uploads

**Comment by Charlotte-Morgan** [comment]
Hi @Rizky could you please provide an estimated implementation schedule for this ticket ?
I would like to see Ash live by the end of November.

@RikkiWeber

**Comment by lucernae** [comment]
Hi @Charlotte-Morgan I think you mentioned the wrong people there 😄 .
I will work on that again after the training. So, hopefully on Friday you can see it on the live site.

**Comment by Charlotte-Morgan** [comment]
Thanks - that would be great

**Comment by gubuntu** [comment]
To confirm further details:
- ash events will be public on staging and production
- PVMBG will get an account equivalent to their account on staging, for them to upload new ash events on production.

**Comment by Charlotte-Morgan** [comment]
@gubuntu - confirm that is my understanding of requirements
@RikkiWeber - to advise otherwise

**Comment by Charlotte-Morgan** [comment]
hi @lucernae and @gubuntu 
I think we have this status now:
Steps to support this:
- [X] prepare everything on staging
- [X] prepare about text for ash and upload to content management system
- [ ] advise PVMBG that its ready
- [ ] ask PVMBG if we should delete any test Volcanic Ash reports and data
- [ ] push the activate button

I will ask @ivanbusthomi to liaise with PVMBG regarding the next 2 steps

**Comment by Charlotte-Morgan** [comment]
@RikkiWeber, @estukriswati the InaSAFE Volcanic Ash Realtime page is ready on staging staging.realtime.insafe.org to go live. Do you have any preference if the test files should be removed from the InaSAFE Volcanic Ash Realtime page before it goes live.

**Comment by Charlotte-Morgan** [comment]
Steps to support this:
- [X] prepare everything on staging
- [X] prepare about text for ash and upload to content management system
**- [X ] advise PVMBG that its ready**
- [ ] ask PVMBG if we should delete any test Volcanic Ash reports and data
- [ ] push the activate button

@estukriswati has requested "Before launching could you please send email to the head of PVMBG about the release plan ?" @RikkiWeber will do this next week when she is back from leave.

**Comment by Charlotte-Morgan** [comment]
hi @lucernae and @gubuntu I think we have this status now:
Steps to support this:
- [X] prepare everything on staging
- [X] prepare about text for ash and upload to content management system
- [X] advise PVMBG that its ready
- [ ] minor tweaks to upload form
- [ ] delete  test Volcanic Ash reports and data
- [ ] push the activate button

**Comment by gubuntu** [comment]
@Charlotte-Morgan can we close?

**Comment by Charlotte-Morgan** [comment]
@gubuntu  - not yet. I think we need to set up an account on production so that people can upload volcanic ash hazard data.

**Comment by Charlotte-Morgan** [comment]
and backup the staging data and migrate some real data

**Comment by Charlotte-Morgan** [comment]
@lucernae  - this is super urgent.
Could you please make user accounts on production for @ivanbusthomi @RikkiWeber @estukriswati and Tory
Please email these people and cc me when the accounts are made.

**Comment by ivanbusthomi** [comment]
Hi @lucernae this is the email that I usually use to email our PVMBG partner: 
* estukriswati : estukriswati@gmail.com
* oktory : toryhebat@gmail.com

**Comment by Charlotte-Morgan** [comment]
rikki.weber@ga.gov.au
ivan.busthomi@dminnovation.org

**Comment by lucernae** [comment]
I created these accounts with default password (I will pass the information to @ivanbusthomi ).
Each users should change their password into something more secure by clicking through these steps:

Go to `Model Admin` page
<img width="408" alt="screen shot 2018-02-20 at 10 43 55" src="https://user-images.githubusercontent.com/831865/36406666-11305d0e-162b-11e8-8603-5bcf60a563b4.png">

Click `change password` link
<img width="691" alt="screen shot 2018-02-20 at 10 44 07" src="https://user-images.githubusercontent.com/831865/36406671-179ce2a2-162b-11e8-9229-cfefc98c2084.png">

**Comment by lucernae** [comment]
Done
