### ISSUE TITLE
Support for Indonesian Ash Report

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#129]
Enable again Indonesian report based on mas @felix-yew requests.

To Do:
 - [x] Refactor code to enable localization @lucernae
 - [x] Translate source string on transifex @felix-yew 
 - [x] Update/compile translations @lucernae
 - [x] UIpdate new docker image and deploy to staging @lucernae
 - [x] User Acceptance Test @felix-yew

**Comment by felix-yew** [comment]
Hi mas @lucernae - the translation in transifex (Django and Realtime) was done.

**Comment by Charlotte-Morgan** [comment]
I am not sure what this request was about?

**Comment by lucernae** [comment]
This is a request to have Indonesian report for Ash. The translation string is now on transifex.
