### ISSUE TITLE
EQ Realtime Tweaks

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#13]
Hi @lucernae
some of the recent changes you have made to EQ realtime page look great.
I really like the filter on size and limited number of reports on the front page.
Here are a few suggested tweaks for the english. I hope this is easy for you. We will demo this at UR 2016 next week and I am making some screenies today.

Please make it say "Recent Large Earthquakes" and "Recent Small Earthquakes"

Would it also be possible to manage future events by making the default filter have todays date

I suggest "Earthquake events with magnitudes greater than or equal to 5 since "
and
"Earthquake events with magnitudes less than 5 since "

The product title
we all call this earthquake realtime but I see its called shake map and InaSAFE Shake Realtime
is this something we want to change?
image

See original ticket at https://github.com/inasafe/inasafe/issues/2783 for discussion.

**Comment by Charlotte-Morgan** [comment]
I think this is done

**Comment by lucernae** [comment]
Closing this
