### ISSUE TITLE
Add Volcanic Ash about text

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#131]
@ivanbusthomi  - please upload the following text for the Volcanic Ash about page using the same styling as in the Earthquake and Flood about pages. You will also need to translate for the Indo version :)
This text has been approved by @RikkiWeber 

Please check that the text on the landing page is the same as the intro paragraph in this text.

cc 
@estukriswati 
---------------------------------------------------------------------------------------
The InaSAFE Realtime Volcanic Ash page contains near real time volcanic ash impact assessments generated prior to or during recent volcanic eruption events in Indonesia.  The volcanic ash hazard models for ash thickness are prepared by Pusat Vulkanologi dan Mitigasi Bencana Geologi (PVMBG) to show the potential ash fallout on the ground. InaSAFE impact assessments are made automatically once a volcanic ash hazard model output is uploaded by PVMBG to the server. This information is used by disaster managers to help them understand the potential scale of a volcanic ash impact and to recommend mitigation activities for the most vulnerable communities. This is particularly important in the lead up to an eruption when communities have an opportunity to prepare for a possible hazard event. 
The InaSAFE Realtime Volcanic Ash platform allows users to see a list and map of the volcanic ash events for which a hazard data set has been uploaded. Volcanic ash events can be sorted or filtered by alert level, volcano name, date and time, eruption height and district. Users can zoom to a volcanic ash event and open the impact report. The platform also allows users to download the volcanic ash impact report, the original hazard data and the impact layer. The hazard data can be used in the desktop version of InaSAFE for further analysis.
The InaSAFE Realtime Volcanic Ash report shows details of the volcanic ash event such as the name and location of the volcano and the results of InaSAFE Realtime Volcanic Ash analysis. The analysis map shows the potential ash fallout classified into 5 classes of ash thickness on the ground:
between 0.01 and 0.1 cm, 
between 0.1 and 2 cm, 
between 2 and 5 cm, 
between 5 and 10 cm and 
greater than 10 cm. 
The InaSAFE Realtime Ash analysis report estimates the number of people affected by the ash in each of 5 fallout classifications based on the thickness of ash on the ground; using modelled population exposure data from World Pop. People are considered to be affected if they are within the area of the event. The InaSAFE Realtime Volcanic Ash analysis also estimates the area of land cover affected, and lists nearby places and airports in the affected area by fallout level. 
Notes:
Volcanic ash is modelled hazard data estimating the thickness of ash on the ground following a volcanic eruption. Volcanic ash thickness is modelled using volcano observations and forecast regional wind data. Each hazard layer is a single scenario model for one intensity of eruption and one wind model. 

Limitations:
The extent and severity of the modelled volcanic ash event may not be consistent with the actual event.
Exposed population varies by the time (day or night, weekends, holidays etc.). Such variations are not considered in the estimates in InaSAFE.
The actual impact on people may differ from the analysis results due to limitations in the accuracy of the data, the analysis model and the behaviour of the local population. It does not include a measure of uncertainty.
For this reason, decisions should not be made solely on the information presented here and should always be verified by ground truthing and other reliable information sources.

**Comment by Charlotte-Morgan** [comment]
this text also needs to be translated and included in the Indonesian landing page

**Comment by ivanbusthomi** [comment]
I noticed that from the current `test ash user` the option to change the about pages has gone.
could you please confirm this @lucernae ?

**Comment by lucernae** [comment]
test ash user doesn't have credentials to change about page. You have to use test user (the superadmin for staging). Then go to staging.realtime.inasafe.org/admin @ivanbusthomi

**Comment by ivanbusthomi** [comment]
Hi @lucernae - I have added the about page for the ash. do you know where to put the translated one?

**Comment by lucernae** [comment]
Mas @ivanbusthomi there is a new column called language, you can put the content based on the language.

<img width="462" alt="screen shot 2017-11-24 at 07 37 21" src="https://user-images.githubusercontent.com/831865/33191288-5e29a1dc-d0ea-11e7-8074-cbb296f4429a.png">

For aesthetic purposes, you can also put the language code in the url (so the Indonesian and English language will have different url)

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi - do you also have the translated pages for Earthquake and Flood? These also need to be translated.

**Comment by Charlotte-Morgan** [comment]
volcanic ash text is translated
