### ISSUE TITLE
Translation - about pages

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#134]
We need to translate and publish the translated content for the about pages for flood and earthquake

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - if this is done, please close the ticket

**Comment by gubuntu** [comment]
done on staging, @ivanbusthomi will copy across when production is updated

**Comment by ivanbusthomi** [comment]
This has been done and I am going to close it. thanks
