### ISSUE TITLE
Separate indicator monitoring to a different worker thread

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#14]
Problem

InaSAFE Realtime monitoring failed to send connection problem notification.
Expected Behaviour

I got emailed when Realtime is not working.
Proposed Solution

Maybe we need to separate worker for InaSAFE Django job and Indicator monitoring.
Or maybe we should try using celery as builtin linux service.

See original ticket at https://github.com/inasafe/inasafe/issues/3230 for further discussion.

**Comment by lucernae** [comment]
Yeah we already separate the worker thread and we also have Rancher support, so it is a lot more reliable now.
