### ISSUE TITLE
Volcanic ash - text

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#142]
We need to review and update text on the volcanic ash landing page and volcanic ash report template to make sure that it clearly describes what the product and service are about and is explicit about any limitations in the use and interpretation of the results.
- [x] template text
- [ ] landing page text
- [ ] about text

cc
@RikkiWeber , @estukriswati

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi 
Please  use the following text strings as notes in the Nearby places table.
This text replaces the words "No nearby cities or airports affected"

Use this note if no records returned:
"No nearby cities or airports are affected by forecast ash fall on the ground in this report.  "

Use this note always :
"This report does not include the potential impact of airborne volcanic ash on aviation services.  Nearby airports may already be affected or become affected in future by ash fall on the ground or other hazards."

ie when there are no records there will be 2 notes

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi 
Please use the following text to create header tokens for the volcanic ash impact report template

**Header text: left side**
Volcano: <name>, <event_date>, <event_time>, <event_timezone>
Position: <x>, <y>
Eruption Column Height (asl): <column_height>
Province: <event_province>
Alert level: <event_alert_level>

**Header text: right side**
Model duration: <duration_days>
Report time: <elapsed_time_since_event_time>
Report expires: <event_date + 1 day>, <event-time>, <event_timezone>

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi 
in the disclaimer text please replace the words "at the surface" with the words "on the ground"

**Comment by Charlotte-Morgan** [comment]
@lucernae  - please change the Volcanic Ash landing page text to say this:
This page contains near realtime volcanic ash impact assessments generated prior to or during recent volcanic ash eruptions in the Indonesia region. Hazard maps of volcanic ash thickness on the ground are produced by Indonesia’s Geological Agency, Badan Geologi (http://www.bgl.esdm.go.id) and used by the Indonesian National Disaster Management Agency (BNPB) to produce InaSAFE impact assessments (http://www.bnpb.go.id or http://realtime.inasafe.org). InaSAFE Realtime Volcanic Ash assessments estimate the potential impact of volcanic ash on the ground. This information is used by disaster managers to help them understand the potential scale of the volcanic ash impact and to undertake mitigation activities.

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi 
I have updated the about page for volcanic ash. The first paragraph, notes and limitations.
Could you please update the Indonesian language page with the new text?

**Comment by ivanbusthomi** [comment]
@Charlotte-Morgan OK - I will update it today. Sorry for the late response.

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi  - can you please give an update on the status of  all 3 text updates in this ticket.

**Comment by Charlotte-Morgan** [comment]
@lucernae to extract text strings used in template to make it easier to update and translate

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan , Sorry for the late response, it's been under my to do list for quite a while.

* Template Text
I have updated the template to match the text that you suggested, but for this one:
   >This text replaces the words "No nearby cities or airports affected"
Use this note if no records returned:
"No nearby cities or airports are affected by forecast ash fall on the ground in this report. "

   I am not sure whether we can do it in the template side, because if I remember correctly it is returned from the processing on the web side. could you pls confirm it mas @lucernae ?

   I am still tweaking sizes of some element to match both english and indonesian version.

* landing page text
I just checked the text in the landing page, and I notice that it is not changed yet. I couldn't find the setting in the admin page to change text in the landing page. Mas @lucernae Do you need my help to change it for you?

* about text
   I have updated the translation, I will check it again to make sure.

**Comment by lucernae** [comment]
mas @ivanbusthomi,

* Template Text: The available token were listed in this file: https://github.com/inasafe/inasafe-realtime/blob/realtime-backport-cherry-pick/realtime/ash/report_text.py . You can also change it if you want by creating pull request to that file.

* Landing page text: These landing page were a static pages. For example in this file for ash:

https://github.com/inasafe/inasafe-django/blob/develop/django_project/realtime/templates/realtime/ash/index.html#L33

You can browse other files too for respective hazard landing page. For example, flood landing page is in https://github.com/inasafe/inasafe-django/blob/develop/django_project/realtime/templates/realtime/flood/index.html

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi and @lucernae  - I am not seeing these changes on the landing page, about page or in the template. These things must be in place before we go live.

@gubuntu

**Comment by ivanbusthomi** [comment]
@Charlotte-Morgan now that @lucernae (thank you Mas) has implemented some updates in the production site, I can start resume the changes for the text there

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan 
I have updated the about text translation in the staging site to include the changes you've implemented for the English one. I can continue with the production site if you are happy with it.

@lucernae - I made a PR to update the landing page in https://github.com/inasafe/inasafe-django/pull/235 to include suggestion above. Could you please check it?

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi  - I've spotted an error in the header info.
The report should expire 24 hours (1 day) after the event date and time.
This is different to the duration of the wind forecast

cc @RikkiWeber 
---------------------------------------------------

here is  the original request from 1 December
@ivanbusthomi
Please use the following text to create header tokens for the volcanic ash impact report template

Header text: left side
Volcano: , <event_date>, <event_time>, <event_timezone>
Position: , 
Eruption Column Height (asl): <column_height>
Province: <event_province>
Alert level: <event_alert_level>

Header text: right side
Model duration: <duration_days>
Report time: <elapsed_time_since_event_time>
Report expires: <event_date + 1 day>, , <event_timezone>

**Comment by Charlotte-Morgan** [comment]
@gubuntu  - when the final change is made to correct the error in the header - we are happy that all the  text requested has been included: landing page, template and about pages.

@RikkiWeber has reviewed and is happy with the content

**Comment by Charlotte-Morgan** [comment]
I think we can close this
