### ISSUE TITLE
Volcanic ash - rounding error

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#143]
## problem ##
The results for people affected by volcanic ash have been rounded too much in the impact report. This means that the estimated number of people affected is misleading.
The volcanic ash realtime report:
![image](https://user-images.githubusercontent.com/5743135/33352253-2c911f40-d4fc-11e7-9860-1ef7af8f785c.png)

The results when run in the desktop:
![image](https://user-images.githubusercontent.com/5743135/33352226-13b45b2c-d4fc-11e7-93f6-4f85f134d61b.png)

Population rounding standard:
Numbers reported for population counts have been rounded to the nearest 10 people if the total is less than 1,000; nearest 100 people if more than 1,000 and less than 100,000; and nearest 1,000 if more than 100,000.

## proposed solution ##
1. change the row heading from People Affected (x1000) to Estimated People Affected
2. change the values in each fall out category to be the rounded value like this
![image](https://user-images.githubusercontent.com/5743135/33352799-ca046a14-d4fe-11e7-802e-78f695032ad6.png)

cc
@ivanbusthomi @RikkiWeber @estukriswati

**Comment by lucernae** [comment]
@Charlotte-Morgan I think I can just go ahead on this one, right?

**Comment by Charlotte-Morgan** [comment]
hi @lucernae - please just go ahead with this one

**Comment by lucernae** [comment]
The table becomes like this now.
<img width="843" alt="screen shot 2017-11-30 at 05 50 53" src="https://user-images.githubusercontent.com/831865/33403591-8cf81f86-d593-11e7-91a6-05ead7e25324.png">

**Comment by Charlotte-Morgan** [comment]
hi @lucernae 
Please make the heading Estimated People Affected or Estimated number of People Affected
Can you show me what the nearby places table and headings will look like too?

Also while you are there - can you fix a type in the low description - the word should be infrastructure
thanks

**Comment by lucernae** [comment]
This is the full preview. Maybe you wanted to change nearby rounding too?

![ash-report](https://user-images.githubusercontent.com/831865/33404678-d0c9604a-d597-11e7-8f74-ee4e9f1e4b47.png)

**Comment by Charlotte-Morgan** [comment]
If the rounding is also removed from the number of people in the nearby places we need to remove the (x1000) from the table header
