### ISSUE TITLE
InaSAFE Ash Realtime Report Text Editing

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#146]
In order to let us easily changed the template and all the strings in it (also tested it directly on staging), I propose we do the following:

- [x] Make Realtime able to receive custom template path (in #145): @lucernae
- [x] Add additional env variable in django's container in staging server to specify the custom path
- [x] @ivanbusthomi can edit the template in a btsync folder and have it synced into staging server.
- [x] @lucernae will extract all translateable string format used in the report in a dedicated file so it can be easily edited (similar with report template concept in InaSAFE v4).

the main bottleneck is still the string because it's a python file, so it has to go through a PR --> docker build --> deployment

@Charlotte-Morgan maybe you want to add something?

cc
@ivanbusthomi @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
Thank you @lucernae 
From my side the out come is that I am looking to have some 'notes' at the bottom of the nearby places table for example. Those notes may be different depending on whether the table has entries or not. The notes will be strings that will need to be translated.

**Comment by ivanbusthomi** [comment]
> Make Realtime able to receive custom template path
> ivanbusthomi can edit the template in a btsync folder and have it synced into staging server.

Hi @lucernae - have you implemented the btsync workflow? I already made some adjustment to the ash template

**Comment by gubuntu** [comment]
implemented and working
