### ISSUE TITLE
EQ Report: edit disclaimer text

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#148]
Can we please make the following changes to the disclaimer text:
remove the statement about rounding 50 fatalities to 0
change the statement about fatalities to say MMI VI not MMI 4 (yup it should be 6)

![image](https://user-images.githubusercontent.com/5743135/34094655-2996bd6a-e422-11e7-872a-3f75137e85c2.png)

**Comment by lucernae** [comment]
I will extract this text so it can be easily edited

**Comment by lucernae** [comment]
It can now be edited from the template.
