### ISSUE TITLE
Update EQ about page

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#149]
Add a statement in the limitations to say that results / estimates and fatalities my vary between versions of InaSAFE

**Comment by Charlotte-Morgan** [comment]
@lucernae  - i'm thinking this should not be done on staging?

**Comment by Charlotte-Morgan** [comment]
The following changes are requested to the earthquake about text

**Comment by Charlotte-Morgan** [comment]
Replace:
_The fatality calculation assumes that no fatalities occur for shake levels below IV and fatality counts of less than 50 are rounded down._
with 
_The fatality calculation assumes that no fatalities occur for shake levels below VI._

Add the following note:
_The estimated number of fatalities and people affected will vary between different fatality functions and different versions of InaSAFE._

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi  - I'm handing this to you because I think it should be done in the production (not staging) environment.  There will also be some strings to translate.

**Comment by ivanbusthomi** [comment]
Thank you for reminding me this @Charlotte-Morgan, I will update it today. I am sorry for the late response.

**Comment by ivanbusthomi** [comment]
It is done in staging, but due to #160 it is not possible to do this in production. 
Once that ticket is fixed, this issue will be also fixed,
thanks
