### ISSUE TITLE
Composition Rendering is not consistent

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#15]
Problem

There were some inconsistencies of the report result generated from QGIS Composition despite they have the same docker environment.
Expected Behavior

Report generated reliably
Environment

QGIS: 2.16.1 QGIS LTR

See original ticket at https://github.com/inasafe/inasafe/issues/3282 for further discussion.

**Comment by lucernae** [comment]
This is a bug in upstream, and was already fixed in upstream.
