### ISSUE TITLE
Nearby places: we need to use the correct field for population

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#153]
### problem ###
The population of nearby places are reported using a different field from the IND_Captial_Population Point_WGS84.shp (common data in Realtime) in earthquake realtime reports to that used in volcanic ash realtime reports. This means that if the same place was affected by an earthquake and a volcanic ash fall; InaSAFE Realtime reports would report a different population for the same place.

example
Earthquake realtime reports use the `Total_Pop `field and volcanic ash reports used the `Cap_Pop_Es` field
. 
### proposed solution ###
Nearby places in realtime reports should be based on the same places dataset and the population for nearby places should be based on the same field.
The field that should be used for both reports is `Cap_Pop_Es` as this estimates the population of the city rather than  the total population of the district or province.

Please use the field in yellow
![image](https://user-images.githubusercontent.com/5743135/34283389-9116aa86-e71f-11e7-9556-3ab8e465338c.png)

### cc ###
@samnawi - please confirm my understanding
@ivanbusthomi @Gustry

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
Based on my current checkout code, I can't find the file that you mentioned: `IND_Captial_Population Point_WGS84.shp`. I only find this layer: `IDN_Capital_City_Point_WGS84.shp` I checked its keyword, it's already set to use `Cap_Pop_Es` not `Total_Popfield`


Perhaps I miss something in the realtime source code structure. But I couldn't find another file. Can you give me some clue @lucernae . Or can you tell me how did you find that the earthquake and ash realtime use different layer?

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni 
I have a btsync file for realtime that looks like this:
![image](https://user-images.githubusercontent.com/5743135/34590465-14e1d5de-f20b-11e7-8314-cd7b4db3e82f.png)
Maybe someone can share a screenie of the data you really use :)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
Now I am not sure that we are talking the same thing. I only checked from the data that sync in from @lucernae 's ansible script.
<img width="542" alt="screen shot 2018-01-05 at 15 57 48" src="https://user-images.githubusercontent.com/1421861/34602167-58ba4bc6-f231-11e7-9a84-29b92ff14573.png">

Perhaps @lucernae can explain what is what.

**Comment by lucernae** [comment]
@ismailsunni I will check it also and let you know after that.

**Comment by gubuntu** [comment]
@lucernae is addressing this now

**Comment by lucernae** [comment]
I think I already fixed this in the past like @ismailsunni said.
I do double check again and copy the new files and confirmed Ash will use `Cap_Pop_Es` from `IDN_Capital_Population_Point_WGS84.shp`. Previously, it was using `IDN_Capital_City_Point_WGS84.shp` but the data inside is the same for `Cap_Pop_Es` field.

For Realtime Earthquake report, I had to dig deeper and come back tomorrow, since it is from legacy code.

**Comment by lucernae** [comment]
Confirmed, Earthquake Report uses Total Pop instead of Cap_Pop_Es.
We fixed it now.

**Comment by Charlotte-Morgan** [comment]
thanks @lucernae

**Comment by gubuntu** [comment]
close @lucernae ?

**Comment by Charlotte-Morgan** [comment]
I think we can close this however - we do have ongoing issues with Places data and exposure data in general for the multiexposure analysis in 4.3
