### ISSUE TITLE
Need to Use Language Specific for Minimum Needs

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe-realtime#156]
### Problem
When checking the flood realtime, I found out that we also use BNPB_en for the Indonesia report.
<img width="872" alt="screen shot 2017-12-28 at 09 32 25" src="https://user-images.githubusercontent.com/1421861/34400175-4d3142ee-ebc1-11e7-88c3-cf50b08d8200.png">

### Expected Behaviour
We should use translated minimum needs also.

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi  - can you please take a look at this? I think this is related to the templates

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 

I think this is not related to the template. You can replicate this in the QGIS actually. The problem is we use one minimum needs profile to run the analysis (BNPN_en). Since the minimum needs profile is not translatable, we will get an English minimum needs even if we use Bahasa Indonesia report. CMIIW @lucernae 

Alternative solution:
1. Use different minimum needs for English and Bahasa Indonesia report
2. Make the minimum needs translatable

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - I think we already have BNPB_id so maybe that is the solution. How do we handle this in desktop?

**Comment by ismailsunni** [comment]
In desktop, you need to run two analysis with those two minimum needs profile (BNPB_en and BNPB_id). So perhaps we need to do this also in the realtime.

**Comment by gubuntu** [comment]
this should be addressed in v4 migration

**Comment by lucernae** [comment]
Yes correct, @ismailsunni then we need to provide BNPB_id to realtime.

**Comment by ismailsunni** [comment]
Providing BNPB_id profile is easy. The problem is how we apply it, since we need to restart QGIS to make InaSAFE use different minimum needs profile (after changing the minimum needs profile, of course), and re-run the analysis.

What do you think @lucernae ?

**Comment by lucernae** [comment]
Whoops. So it still needs a restart? Is there no way to trigger profile changes programmatically? Did you concerned with the Behaviour in InaSAFE Desktop or in Realtime? I mean, in InaSAFE Realtime we can just feed the task into a worker for different language. But I prefer more elegant solutions if any.

**Comment by ismailsunni** [comment]
For realtime.
Well, IIRC, we need to restart since the fields for minimum needs are dynamic and created when InaSAFE starts (CMIIW @myarjunar or @Gustry)

For the current system, how do you create two report for each English and Bahasa Indonesia? IIRC, changing the language also needs to restart InaSAFE.

**Comment by Gustry** [comment]
Yes, see PR about avoiding restarting QGIS: https://github.com/inasafe/inasafe/pull/3976

@lucernae Is the worker starting QGIS?

**Comment by lucernae** [comment]
@ismailsunni @Gustry I didn't restart the worker when changing language. It
happens in one thread. I'm not even thinking about restarting Qgis and it
just works. I will check how this is possible  when refactoring the code.

**Comment by lucernae** [comment]
Can be concluded, I think.
