### ISSUE TITLE
Realtime Volcanic Ash Testing

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#16]
See original ticket at https://github.com/inasafe/inasafe/issues/3285 for further discussion
The old ticket in https://github.com/inasafe/inasafe/issues/2491 has become too long to track. Now that we are in the testing stage, I propose we move the discussion regarding the testing to this new ticket. I will keep the old ticket open as future reference.

Old ticket link: https://github.com/inasafe/inasafe/issues/2491
Some notable reference:

    link to staging server (online): http://staging.realtime.inasafe.org/realtime/
    link to temporary staging server: http://196.214.55.116:61100/realtime/
    login steps : #2491 (comment) https://github.com/inasafe/inasafe/issues/2491#issuecomment-252524564
    current landing page at temporary staging server

See original ticket at https://github.com/inasafe/inasafe/issues/3285 for further discussion.

**Comment by gubuntu** [comment]
assuming we can close this since Ash has been extensively used and tested on staging and is slated to move to produciton in Nov. Open new, specific issues if any arise
