### ISSUE TITLE
Indonesian about page in production site

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#160]
### Problem
I noticed there is a difference in the admin page for staging site and production site for managing the coreflatpages.
![image](https://user-images.githubusercontent.com/7351977/34705211-69af476c-f531-11e7-8e6f-680bd103379a.png)

When I tried uploading the Indonesian version of about page to the production site, it created a new tab instead of changing the english text when I changed the language.
Then I deleted it to avoid creating confusion from user. I didn't take a screenshot when that happen, but this is what I remember seeing
![image](https://user-images.githubusercontent.com/7351977/34705513-7d4df924-f533-11e7-874f-35148f9995a2.png)

There is no problem in the staging environment, so my guess is that 
* maybe there is some logic that has not been implemented in the production site, 
* or that I am not adding the Indonesian about page in the production site properly.

### Expected Behaviour
The about page should be properly implemented for both english and Indonesian in the production environment.

### Environment
* InaSAFE : Realtime (Production site)
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
make it happy

CC: @Charlotte-Morgan @gubuntu @lucernae @ismailsunni @myarjunar

**Comment by gubuntu** [comment]
this will be resolved once updates are deployed to production

**Comment by lucernae** [comment]
I updated production site to allow this, but hides Volcanic Ash
