### ISSUE TITLE
Separate realtime package

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#162]
Child issue of #97 

This repo is going to be specific for InaSAFE Realtime Hazard processing.
Python modules here will handle receiving raw hazard data and convert it into InaSAFE layer.

What needs to be done:

- [x] Remove headless package
- [x] Refactor realtime package functionality to use InaSAFE core
- [x] Refactor shake grid handling by using InaSAFE core to convert it into Shake Hazard
- [x] Refactor Flood geojson handling by using InaSAFE core to convert it into Flood Hazard
- [x] Refactor Ash tif handling by using InaSAFE core to convert it into Ash Hazard
- [x] Implement unittests and run it in docker/celery/travis

**Comment by gubuntu** [comment]
can we close?

**Comment by lucernae** [comment]
Yes!
