### ISSUE TITLE
Separate Headless package

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#163]
Child issue #97 

We need to move headless package into a different repository.

- [x] Move headless package into different repository
- [x] Implement unittests using docker/celery/travis

Refactor previous celery tasks to use InaSAFE v4:
- [x] Run analysis with input: hazard, exposure, aggregation or CRS
- [x] Extract metadata from a given InaSAFE Layer
- [ ] Generate report using custom report template/params

Add new celery tasks:
- [x] Run multi exposure analysis

**Comment by ismailsunni** [comment]
For the record, we put the headless in https://github.com/inasafe/inasafe-headless

**Comment by gubuntu** [comment]
can we close?

**Comment by ismailsunni** [comment]
I think so.
