### ISSUE TITLE
Template update for volcano event time zone information

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#174]
Since the implementation of volcano event time zone information, the template elements for this information become too long and overlap with the next element. 
![image](https://user-images.githubusercontent.com/7351977/35561801-066a6a60-05e4-11e8-89a6-36fc38c81b2b.png)

We need to update the template so that the information can be shown nicely. My suggestion is to add a new line to accommodate it.

CC @lucernae @myarjunar @ismailsunni @Charlotte-Morgan @estukriswati @gubuntu

**Comment by ismailsunni** [comment]
What's the string after `Asia/Makassar`?

**Comment by ivanbusthomi** [comment]
It is the +0800 @ismailsunni to indicate its difference with UTC

**Comment by ismailsunni** [comment]
@ivanbusthomi can you tweak the template to make it two lines? e.g. first line for name, second line for timestamp.

**Comment by ivanbusthomi** [comment]
@ismailsunni this is the tweaked template. I basically split the element using an expression. I think it worked as a quick fix for now.
![image](https://user-images.githubusercontent.com/7351977/35620962-653ab2f8-06b5-11e8-945b-e69581cd72e7.png)

**Comment by ismailsunni** [comment]
@ivanbusthomi sorry if I misunderstood. What's the element that you split? Perhaps we should give more granular element / item so that you can just concat if needed. Easier to concat than split, I think.

**Comment by ivanbusthomi** [comment]
@ismailsunni the element that I split is in
https://github.com/inasafe/inasafe-realtime/blob/f79ecb6c25bfb2c96afa7fd9a96f0bddd3146dca/realtime/ash/report_text.py#L43-L48

I used the `left` and `right` expression.
`left('[report-timestamp]',strpos('[report-timestamp]',','))` and
`right('[report-timestamp]', length('[report-timestamp]') - strpos('[report-timestamp]',','))`
basically I split it using the `,` character.

the other element that I also split using the same logic is in 
https://github.com/inasafe/inasafe-realtime/blob/f79ecb6c25bfb2c96afa7fd9a96f0bddd3146dca/realtime/ash/report_text.py#L54-L60

I believe this is a quick fix for the current version of realtime, as I want to confirm again with Ibu @estukriswati from PVMBG to get her feedback again on the template.

Why I choose this approach is because, in the new template that we are going to have as per ticket https://github.com/inasafe/inasafe/issues/4724, the information that we need is already granular ( I guess?) since it is stored separately as an extra keyword item. So I can already access them one by one from the template and concatenate them if I need.

I am open to any suggestion, hehe. I am not sure how we implement it in the next version of realtime, but if you think it is easier to add/convert it as a granular item, I am more than happy to implement it.

**Comment by ismailsunni** [comment]
Ah I see, this is for current realtime. It looks good then.
