### ISSUE TITLE
Ash Realtime: add the KRB data as an overlay on the impact report

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#18]
Problem

Friends from PVMBG have requested that realtime ash reports include the KRB pyroclastic boundaries as context data
Expected Behaviour

The boundaries will be shown as lines over the ash model.
the lines will be coloured but no fill
Proposed Solution

The map should show the official data from PVMBG
@willi09 will share the KRB data and volcano point data when it is ready.

@ivan will add the data to the realtime data share and the map can be updated
cc

@lucernae @timlinux

This is not a blocker for the release of ash realtime

See original ticket at https://github.com/inasafe/inasafe/issues/3337 for further discussion.

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - do we have this data yet?

**Comment by ivanbusthomi** [comment]
I think we can close this, since PVMBG have changed their request, and only want to show the evacuation route.
https://github.com/inasafe/inasafe-realtime/issues/69#issuecomment-287281363

**Comment by Charlotte-Morgan** [comment]
closing this
