### ISSUE TITLE
Realtime production: landing pages

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#181]
## problem ##
There are still some inconsistencies with content and translation on the landing pages for InaSAFE realtime.

1. The landing page text for flood is still in English on the Indonesian page
2. The menu for about pages is not shown on the landing page in Indonesian

![image](https://user-images.githubusercontent.com/5743135/35890712-007b9e50-0bf5-11e8-9b23-ff18e351415b.png)

## proposed solution ##
The landing page text should be in the language of the page
The about pages should be visible in both the English and Indonesian versions

I think this needs to be working before the migration. Please reassign to relevant people in the team.

**Comment by gubuntu** [comment]
LGTM
