### ISSUE TITLE
Realtime exposure data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#182]
We need to review, update, document and share the exposure data used by realtime so that the same data can be used in the desktop environment or updated / replaced by others in future. This means cleaning up some legacy data.

Here are some suggestions of what needs to be done now as part of the migration to 4.3 and handover to BNPB - with suggestions of key people
- [ ] Update worldpop 2010 with worldpop 2015 as per discussion with BNPB @Charlotte-Morgan
- [ ] Prepare and document a single populated places data set that is used by all hazards
- [ ] Develop and share an airports data set that is compatible with the InaSAFE 4.3 multi exposure metholodology
- [ ] Document the methodology for the creation of custom data sets - ie generalised worldpop, landcover and populated places data. @samnawi 
- [ ] Ensure exposure data are suitably named and have full metadata including sources. @samnawi 
- [ ] Share the data with metadata and key words on GeoNode - if licensing supports this @felix-yew 
- [ ] Ensure all reports, landing pages etc are updated to reflect the data names and sources @ivanbusthomi 
- [ ] Update realtime analysis routines to use the new data @lucernae 
- [ ] Include exposure data maintenance in training materials @gubuntu

**Comment by Charlotte-Morgan** [comment]
@gubuntu - lets discuss this, maybe you already have this in your schedule; if not the DMI team will need to know when and how they can contribute to the update and maintenance of the exposure data.

cc @timlinux FYI

**Comment by Charlotte-Morgan** [comment]
I propose a new folder structure for the realtime data
realtime data
- /context
-/exposure

ie no middle hazard specific folders

**Comment by ismailsunni** [comment]
Hi, @lucernae @ivanbusthomi don't forget to check this. Just to make sure both of you use the same path in code and in the sync data.

**Comment by lucernae** [comment]
We managed to do this and all files were sync'd via BtSync
