### ISSUE TITLE
Ash upload form - translation

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#185]
This is probably a papercut - but there are a few fields that are not translated in the volcanic ash upload form.
![image](https://user-images.githubusercontent.com/5743135/35955604-99f49402-0ce4-11e8-9de6-d8a8838270b4.png)

**Comment by Charlotte-Morgan** [comment]
this is done we can close this

**Comment by lucernae** [comment]
Updated into this:
<img width="651" alt="screen shot 2018-02-14 at 15 02 54" src="https://user-images.githubusercontent.com/831865/36193370-2c3c0c3e-1198-11e8-8b1b-3f5964431eac.png">
