### ISSUE TITLE
Ash upload form - minor edits

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#189]
hi @lucernae and @ivanbusthomi 
@RikkiWeber has reviewed the volcanic ash realtime form and has requested some minor changes to the text to make things very clear. I do not expect this will require any other changes to tokens etc - it should be cosmetic UI stuff.
This will need to be replicated in the translation #185 

Please change:
_Timezone_ to **Event timezone**
_Eruption height in metres. Calculated from the vent height_ to **Eruption height in metres (above vent height)**

these are highlighted below
![image](https://user-images.githubusercontent.com/5743135/36003438-3294c02c-0d82-11e8-8be1-a295061dfbc6.png)

**Comment by Charlotte-Morgan** [comment]
I see this is done - we can close this

**Comment by lucernae** [comment]
<img width="632" alt="screen shot 2018-02-14 at 15 01 06" src="https://user-images.githubusercontent.com/831865/36193299-f94c3cd6-1197-11e8-8d03-f840dec47c55.png">


Updated into this.
