### ISSUE TITLE
Flood Realtime : Minimum Needs provided for affected or IDP?

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#19]
# Problem

The report of minimum needs in Flood realtime report appears to refer to the affected people rather than the IDP.

Which stuff that should be referred by the system to calculate the result?

# Expected Behaviour

As the feedback from BPBD DKI Jakarta, the minimum needs should be provided refers to the number of IDP.

If we refer to the InaSAFE desktop, it should refers to the number of IDP.

See original ticket at https://github.com/inasafe/inasafe/issues/3342 for further discussion.

**Comment by Charlotte-Morgan** [comment]
This sounds like an exposed vs displaced situation?

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - can you please test on the desktop and work out what the number should be

**Comment by Charlotte-Morgan** [comment]
@ismailsunni  - this might be fun for you :)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan or @ivanbusthomi 
I think this issue is already fixed. I checked in the current realtime and in the code, all is good:
sample result: http://realtime.inasafe.org/media/reports/flood/pdf/2017122805-6-rw-map.pdf
the code:
```
        total_idp = total_affected * FloodEvent.IDP_RATE

        # calculate new minimum needs
        min_needs = self.impact_data.minimum_needs
        for k, v in min_needs.iteritems():
            for need in v:
                need['amount'] = need['value'] * total_idp
```

I think we can close this, don't we?

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - could you please confirm and close this ticket if its already fixed?
