### ISSUE TITLE
InaSAFE Realtime Flood template need fix.

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#190]
We have new flood in Jakarta this week and I saw the template still using wrong population range.

http://realtime.inasafe.org/realtime/flood/impact-map/2018020905-6-rw/en/

I need to recheck this, I thought we already fixed it.

**Comment by Charlotte-Morgan** [comment]
@samnawi - can you look at realtime productions and check if there is a problem please

**Comment by lucernae** [comment]
@myarjunar this needs to be fixed in Realtime v4

**Comment by ivanbusthomi** [comment]
I think we can close this issue since it will be fixed once the v4 is implemented.
