### ISSUE TITLE
Volcanic Ash workflow

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#193]
We need to review the volcanic ash upload workflow for when  InaSAFE Realtime Volcanic Ash is live.
### problem ###
PVMBG might normally prepare multiple models (future predictions of ash fall) that they want to test in Realtime but not all should be made public.

This has been fine all the time the realtime system has been a test environment but when it goes live - how will the public only see the 'release' version?

### options to consider ###
PVMBG continue to test in a staging environment
PVMBG undertake testing in the desktop environment
PVMBG have some admin control over which data are visible to the public
Add a 'test' button to the upload form that so all data and results are restricted and then an option to change the test status to 'public' status later

### cc ###
@gubuntu @RikkiWeber @ivanbusthomi @estukriswati

**Comment by gubuntu** [comment]
I don't think this should be a release blocker: either of the first two options could be chosen to start with and then we can implement the third option (with a test button in the app) if PVMBG would like to go that route.

**Comment by Charlotte-Morgan** [comment]
perfect - thanks @gubuntu 
@ivanbusthomi - this will be something to cover when you next meet with PVMBG to demo the new system

**Comment by lucernae** [comment]
Done
