### ISSUE TITLE
Volcanic Ash data backup

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#196]
We need to backup all volcanic ash data and analysis products from staging.realtime.inasafe.org and archive this file at DMI.

It would be great to also migrate the real event data to the production site if possible

@RikkiWeber @estukriswati

**Comment by ivanbusthomi** [comment]
@Charlotte-Morgan 
At the moment, there are 68 events in the staging environment of Realtime volcanic Ash. We tried to identify which one is test data, and which one is real event. The test data then removed from the staging after making sure it was properly backed up.

The complete list can be found here.
https://docs.google.com/spreadsheets/d/1XuWCJUgJgasU1ixr0J1kaeylKZ-u4eh-vegX5H5FNaQ/edit#gid=1940424445
___
CC @gubuntu @lucernae @timlinux

**Comment by lucernae** [comment]
I don't think we managed to do this.
But we will close it.
