### ISSUE TITLE
Polish landing page terminology

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#200]
It would be great to have some consistent terminology on each landing page. 

Right now we have:
InaSAFE Volcanic Ash
InaSAFE Flood Realtime
InaSAFE Realtime Earthquake Reports

Proposed:
InaSAFE Realtime Volcanic Ash
InaSAFE Realtime Flood
InaSAFE Realtime Earthquake

We could  look at the header above the map too

**Comment by lucernae** [comment]
Done
