### ISSUE TITLE
Migrate old MMI Contours from InaSAFE 3.5

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#203]
# Problem

We need to convert the whole mmi contours of InaSAFE 3.5 into a postgis table for easy migration.

# Plan

![mmi contours migration](https://user-images.githubusercontent.com/831865/36718190-7471dc32-1bd3-11e8-933f-046024155825.png)

mas @ivanbusthomi , you only need to worry about the left side.

The task is described as follows:

1. We need to clone mmi layers data from django media folders and saved it into the postgis database.
2. The data is on the server: `ssh realtime@realtime.inasafe.org -p 9223`. You can go into the directory using ssh, sftp, or rsync (to copy the file across machines).
3. Specific data for mmi contours is on this directory: `/home/web/media/earthquake/mmi_output`
4. It contains lists of zipped file mmi-contours. Inside it is a shapefile. Copy these zipped  files to your own machines. Test automations on your own machines, not from this folder. Spoilers: It's around 600MB size. You can copy it using rsync, and use the same rsync command whenever you want to sync these data from live server.
Example: `rsync -avz -e "ssh -p 9223" realtime@realtime.inasafe.org:/home/web/media/earthquake/mmi_output/ <folder_in_your_machine>`
5. Create postgis table to save the contours data:

Field explanations:
- shake_bmkg_string: shake id provided from bmkg, you can get it from the zip name.
- geom: geometry of a particular polygons that you want to save (from the shp file you're trying to import)
- mmi_level: the MMI level of that geometry

6. Automate to extract all zip files, and ingests shapefile to save each polygon with corresponding mmi level and shake id into the database.

7. This process needs to be executed easily whenever we want to update the database with new mmi contours.

CC @timlinux

**Comment by lucernae** [comment]
CC @ivanbusthomi 

Basically what we want to do is for you is to populate the sql database with this information in each rows:

- shake_bmkg_string
- geom (the line/polygon)
- mmi_level
- properties for the row (the other values present in the column of each row of original shp files. Properties values needs to be filled in a json encoded format). This column is an addition from the diagram above (it was not there previously).  I think we also need to save this information.

If you already have this database (you have done converting the shapefile to postgis for every shakemap). Please put your script somewhere on github (it could be a gist, or if you are familiar, you can create your own git repo for this) and also your database dump (we will call this Raw DB).

From your database dump, either you (@ivanbusthomi) or @gubuntu  should be able to create an sql script to take the values from Raw DB and move it over to Realtime DB (the one that already have a fixed structure/schema).

This entire process needs to be scripted, so we can rerun it again at migration day and have the result quickly updated to be moved over to production database :D.

**Comment by lucernae** [comment]
And this is the sql schema of the MMI contour table for the upcoming database:

This schema is meant as a reference so you know which field is which, so it will help you to create the script for moving the data from Raw DB into Realtime DB.

Also, @ivanbusthomi @gubuntu please write Readme to describe the procedure of what should I do to use the script in production (the chain of command/script I need to make from inside the postgis containers).

```
-- auto-generated definition
create table realtime_earthquake
(
  id                   serial                   not null
    constraint realtime_earthquake_pkey
    primary key,
  shake_id             varchar(50)              not null,
  magnitude            double precision         not null,
  time                 timestamp with time zone not null,
  depth                double precision         not null,
  location             geometry(Point, 4326)    not null,
  location_description varchar(255)             not null,
  shake_grid           varchar(100),
  felt                 boolean                  not null,
  mmi_output           varchar(100),
  generated_time       timestamp with time zone,
  hazard_path          varchar(255),
  inasafe_version      varchar(10),
  source_type          varchar(30)              not null,
  analysis_task_id     varchar(255)             not null,
  analysis_task_status varchar(30)              not null,
  report_task_id       varchar(255)             not null,
  report_task_status   varchar(30)              not null,
  shake_grid_xml       text,
  analysis_task_result text,
  mmi_output_path      varchar(255),
  report_task_result   text,
  constraint realtime_earthquake_shake_id_60b1eea6399d88a7_uniq
  unique (shake_id, source_type)
);

create index realtime_earthquake_location_id
  on realtime_earthquake (location);

create index realtime_earthquake_shake_id_7d3cc59442d39357_like
  on realtime_earthquake (shake_id);

create table if not exists realtime_earthquakemmicontour
(
  id            serial                      not null
    constraint realtime_earthquakemmicontour_pkey
    primary key,
  geometry      geometry(LineStringZ, 4326) not null,
  mmi           double precision            not null,
  properties    text                        not null,
  earthquake_id integer                     not null
    constraint realti_earthquake_id_1edcd8d2ccf76dd4_fk_realtime_earthquake_id
    references realtime_earthquake
      deferrable initially deferred
);

create index if not exists realtime_earthquakemmicontour_b8ad623c
  on realtime_earthquakemmicontour (earthquake_id);

create index if not exists realtime_earthquakemmicontour_geometry_id
  on realtime_earthquakemmicontour (geometry);
```

**Comment by ivanbusthomi** [comment]
HI @lucernae this is the gist link. I'm still updating it
https://gist.github.com/ivanbusthomi/92b9cb911a5465418595145544624a93

And for,
> Basically what we want to do is for you is to populate the sql database with this information in each rows:

by `each rows` do you mean `each columns` ?

**Comment by lucernae** [comment]
each rows too, for example one MMI file might contains multiple rows (different MMI lines) and multiple columns (different values for each rows).

**Comment by gubuntu** [comment]
@lucernae you need to check the Django models in this and other Django apps - the ones above are applying the incorrect index on geometry columns. It must be a gist index, not the default btree index (which is useless on geometry)

@ivanbusthomi I've commented on your gist page

**Comment by lucernae** [comment]
I mean, I'm pretty sure it will be spatially indexed. It was a default setting on django gis models and gis field.

**Comment by gubuntu** [comment]
@lucernae it seems your model is using db_index instead spatial_index https://docs.djangoproject.com/en/2.0/ref/contrib/gis/model-api/#spatial-index. It's generating the wrong sql above. So you probably need to tweak your model.

**Comment by ivanbusthomi** [comment]
This is the result that I received while adding the contour shapefiles to the database
Grid missing = 
`20160302195429
20160302200008
20161116211705`

Contour missing or uses different names =
`20150821201238
20160302195429
20160302200008
20161116211705
20170411070207
20170411095547
20170420180513
20170420235401
20170421110504
20170421220650
20170422182131
20170424010600
20170424131827
20170425043403
20170426115641
20170427140313
20170429032918
20170429033724
20170429042741
20170429170644
20170430005650
20170430213350
20170430233729
20170502171623
20170505051835
20170505072015
20170505140958
20170506172100
20170507141626
20170507142141
20170507143634
20170507144252
20170507182918
20170509160338
20170510135005
20170511005657
20170511021820
20170511022820
20170511155614
20170511220602
20170512045038
20170512232757
20170513193458
20170514105146
20170514234822
20170515012911
20170515020025
20170515065300
20170515073550
20170515115444
20170518193115
20170518205150
20170519184845
20170520101126
20170520190834
20170520212436
20170521125457
20170523161812
20170524040609
20170524161439
20170524234931
20170525175008
20170526062539
20170526111954
20170528101850
20170528180432
20170529032340
20170529045857
20170529073226
20170529214021
20170529220833
20170530144947
20170530153257
20170530200200
20170531095922
20170531114205
20170601042150
20170601114344
20170602014429
20170602055923
20170602130402
20170603102208
20170605172439
20170606221459
20170607000339
20170607123529
20170607195456
20170608024142
20170609223440
20170611125031
20170611140731
20170611205111
20170612062001
20170612113504
20170612183505
20170612225134
20170614052706
20170617063859
20170617212833
20170618042711
20170618232212
20170619114358
20170619143245
20170620214746
20170621012601
20170622055231
20170622171226
20170622214331
20170623185556
20170624072455
20170624223855
20170626201727
20170627061011
20170627220010
20170701121613
20170703060030
20170704110516
20170704151629
20170704192232
20170704210439
20170705023308
20170706002040
20170706185451
20170707072609
20170707104819
20170708014756
20170708015200
20170708070512
20170709055326
20170710100258
20170710203001
20170710212211
20170711002911
20170711082927
20170711174821
20170713163015
20170713213515
20170714082959
20170714085725
20170714171300
20170714230540
20170715191706
20170716103538
20170717231906
20170718002855
20170718113653
20170718125815
20170718155152
20170719012531
20170720111643
20170720114149
20170720152958
20170721142904
20170721160819
20170723103345
20170723150015
20170723192858
20170723203330
20170726062801
20170726070227
20170726171038
20170727191255
20170727205512
20170728022918
20170729130028
20170730142350
20170731113730
20170731113846
20170731210501
20170801105632
20170801113957
20170802165832
20170802165925
20170803231836
20170805212326
20170806043240
20170809185407
20170810070638
20170810090430
20170810090435
20170810130211
20170811061629
20170811224048
20170812142706
20170812171723
20170813101258
20170813123617
20170814223421
20170815065417
20170815110501
20170816094731
20170816111318
20170818071213
20170819040542
20170820081055
20170820191038
20170821115133
20170825073413
20170825130236
20170825223044
20170827034918
20170827070656
20170827090013
20170828081014
20170829060734
20170901001116
20170901060158
20170901105218
20170901193444
20170902103710
20170903021144
20170905024756
20170905095213
20170909101601
20170909171011
20170911094645
20170915194126
20170916213344
20170918073227
20170918184816
20170919052145
20170919055554
20170920094605
20170920173535
20170920201732
20170920232953
20170921070409
20170921090334
20170921091407
20170921200818
20170922083608
20170922173847
20170923084151
20170923120752
20170924064121
20170924070023
20170924122300
20170924174859
20170925031434
20170925051035
20170925150700
20170925172201
20170926011517
20170926051144
20170926125115
20170926152709
20170926170311
20170927021306
20170927182315
20170927200902
20170928010604
20170928011245
20170928112929
20170928133221
20170928140033
20170928172052
20170928183235
20170929000058
20170929060137
20170929082712
20170929122549
20170929142922
20170929172018
20170929173123
20170929174030
20170929175052
20170929180050
20170929182307
20170929183553
20170929194857
20170929201204
20170930035725
20170930083116
20170930173459
20170930175818
20171001062021
20171001123025
20171001174158
20171001185418
20171001193807
20171002054808
20171002092256
20171002094101
20171003220124
20171004000312
20171004063928
20171004134735
20171004204115
20171005110116
20171005112812
20171005115910
20171005125051
20171005131947
20171005144641
20171005193408
20171005200436
20171005203215
20171005210302
20171005220627
20171006061133
20171006071431
20171006081321
20171006082028
20171006083052
20171006102825
20171006112345
20171006162342
20171006215900
20171006223422
20171007010016
20171007014216
20171007085044
20171007162505
20171007181102
20171008111120
20171008115943
20171008122148
20171008135442
20171008173719
20171008184343
20171008193415
20171008193902
20171008212618
20171008222700
20171009003733
20171009120944
20171009161004
20171009174724
20171009175018
20171009235333
20171010011942
20171010012743
20171010052347
20171010070956
20171010160711
20171011020123
20171011061018
20171011233039
20171012235620
20171013220205
20171013233059
20171013233853
20171014202936
20171015022733
20171015042913
20171015044519
20171015055309
20171015192853
20171016052005
20171016085302
20171017211233
20171018203427
20171018204536
20171019084728
20171019104915
20171019175353
20171020042327
20171020073606
20171020073715
20171021083719
20171023192046
20171023200946
20171023232427
20171024013557
20171024110831
20171024175218
20171025084754
20171025183809
20171025190302
20171025191243
20171026050406
20171026075446
20171026091821
20171028191521
20171028192950
20171028200656
20171029201313
20171031054145
20171031073138
20171031120804
20171031184932
20171031185507
20171031190827
20171031192313
20171031194212
20171031215555
20171031234746
20171101012437
20171101015635
20171101080828
20171101103939
20171101124416
20171101142826
20171101215021
20171102100007
20171102101621
20171103000709
20171106162635
20171107095059
20171108142824
20171108221934
20171109022133
20171109045826
20171109060253
20171109101531
20171110101050
20171110210249
20171111102205
20171111210259
20171111211957
20171117110711
20171118231146
20171119014118
20171119025028
20171119201230
20171119214208
20171120003930
20171121064625
20171121213643
20171121224708
20171122081550
20171124144509
20171125161907
20171125181602
20171125202934
20171127120117
20171128162518
20171129203425
20171129212301
20171130001059
20171130065825
20171130152642
20171201071055
20171203162916
20171204000130
20171204000636
20171204072416
20171204185651
20171205155729
20171205191804
20171206035058
20171206051902
20171206231132
20171206234249
20171207031730
20171207073838
20171207222029
20171207235751
20171208193225
20171209004204
20171209064232
20171209101918
20171210212504
20171211045926
20171211165822
20171211185119
20171212000425
20171212092741
20171213203730
20171215214927
20171215235416
20171216000321
20171216043151
20171216072650
20171217080054
20171217093146
20171217191258
20171217225320
20171218221509
20171220095545
20171222051458
20171222172606
20171223004116
20171223215608
20171224224207
20171225195211
20171226104947
20171226122908
20171227021846
20171227141724
20171228185214
20171229002451
20171230021431
20171231155241
20171231215735
20180101103215
20180101132731
20180101143022
20180101174019
20180103095803
20180103173712
20180103214614
20180104013620
20180105030234
20180105164132
20180106135446
20180106173133
20180106223945
20180107181551
20180108225105
20180109124240
20180111090347
20180111164226
20180112145035
20180113045354
20180113210301
20180114115903
20180115133618
20180115223958
20180117094745
20180117112552
20180117202535
20180118101941
20180119005315
20180121051548
20180123034955
20180123133450
20180123133936
20180124003831
20180124074015
20180124084905
20180124133708
20180124140158
20180124194005
20180126115245
20180126171717
20180126174819
20180128011142
20180129210108
20180129222644
20180129233041
20180130045949
20180130191648
20180131080011
20180131090503
20180201132700
20180202072513
20180202125914
20180203114441
20180204062352
20180205025933
20180205071219
20180205083143
20180208165726
20180209141701
20180209162430
20180210073607
20180210174019
20180211141020
20180212165653
20180214002457
20180214071018
20180214135824
20180215043315
20180215053354
20180216093714
20180216121800
20180216142131
20180216154514
20180216203242
20180217090016
20180217153206
20180218020109
20180218114014
20180218115211
20180219174301
20180220163351
20180221084922
20180222023046
20180222142408
20180222144105
20180223163213
20180223164851
20180223230938
20180224081714
20180224170701
20180225174937
20180225181056
20180225184739
20180226004923
20180226011649
20180226015200
20180226032216
20180226041649
20180226093043
20180226101641
20180226162452
20180226165732
20180226203922
20180227142407
20180227162445
20180228095024
20180228103540
20180228121534
20180228122649
20180228184021
20180301084009
20180301102131
20180301121427
20180301131110
20180301161251
20180302092438
20180302161345
20180302191937
20180303040809
20180303043539
20180303094825
20180303153733
20180304101515
20180304102415
20180304104855
20180304194505
20180305034532
20180305145835
20180305203335
20180306103144
20180306174534
20180306202453
20180306211816
20180307093748
20180308103823
20180308105543
20180309183031
20180310190723
20180311014114
20180311022106
20180311090622
20180311185233
20180312130025
20180313082433
20180313113752
20180314121849
20180314212606
20180315081933
20180315113331
20180316020418
20180316083518
20180316143320
20180318125428
20180318183932
20180318205404
20180319142843
20180319184045
20180320044011
20180320193714
20180320200230
20180321105147
20180321181250
20180321223317
20180321232226
20180322071234
20180325160238
20180326031917
20180327055158
20180328015639
20180329013853
20180329015504
20180329103808
20180330040326
20180330140545
20180330154855
20180330231045
20180331180836
20180401025405
20180401203342
20180403161854
20180405064605
20180406145150
20180407032349
20180407054903
20180407074903
20180407125329
20180408230856
20180409185115
20180411091256
20180412004108
20180412085049
20180412131212
20180413110228
20180413142209
20180414155655
20180414181907
20180414214753
20180415010648
20180415170005
20180415192334
20180416023512
20180416054512
20180416131443
20180417094401
20180417095659
20180417120038
20180417134820
20180418132835
20180418141143
20180418163025
20180418233246
20180419203435
20180421121112
20180421181940
20180421183632
20180421222122
20180422093357
20180422095523
20180423100323
20180423102035
20180423110946
20180423144151
20180423151843
20180423195405
20180424100956
20180424224457
20180426100851
20180426165856
20180427000016
20180427112140
20180427175933
20180430001311
20180709124240`

**Comment by lucernae** [comment]
I'm going to close this. The old countours were migrated to postgis table.
Thanks for everyone involved!
