### ISSUE TITLE
Suggestions to rework Volcano and Volcanic Ash Icon

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#21]
Problem

When we had Codesprint last week, our partners at PVMBG said that the current icon for volcano and volcanic ash are not representing the event intuitively enough.

According to them, the icon for the volcano is better suited as the icon for volcanic ash because the logo for volcanic ash is a little bit harder to understand the meaning/context/association with the hazard. To act as volcano icon, they suggest a simpler design without ash coming out of the peak.

Expected Behavior

We should have icon/logo that user can intuitively understand so that they can associate the hazard better just by looking at the logo without additional text to emphasis the idea.

See original ticket at https://github.com/inasafe/inasafe/issues/3347 for further discussion.

**Comment by Charlotte-Morgan** [comment]
@timlinux and @MariaSolovyeva  - I think this belongs in the InaSAFE tickets not realtime

**Comment by gubuntu** [comment]
reverting to inasafe/inasafe#3347 @ivanbusthomi
