### ISSUE TITLE
Earthquake header not showing proper information

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#213]
In the testing environment, the earthquake header showing not correct information.
![image](https://user-images.githubusercontent.com/7351977/39112877-11553598-4704-11e8-8419-b4698d7e8e85.png)

when I check the template in the desktop, I can't find the issue.
![image](https://user-images.githubusercontent.com/7351977/39115026-d15e1bf6-470a-11e8-9689-d5ccb0de06b2.png)

I downloaded the grid xml from the same event in the testing site. So my guess is:
* missing `eartquake_source` keyword: Maybe the testing site is not assigning this keyword yet, so the template can not find it in the hazard keyword
* minus in time: maybe issues with the server time?
---
CC @Charlotte-Morgan @timlinux  @ismailsunni @myarjunar @lucernae

**Comment by lucernae** [comment]
Fixed. Thank you.
