### ISSUE TITLE
Realtime 4 template disclaimer updates

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#216]
We need to make some minor changes to realtime v4  report disclaimers to reflect the new exposure data and explain the limited analysis extent.

**In the earthquake report disclaimer:**
![image](https://user-images.githubusercontent.com/5743135/39412766-c95b2b92-4c64-11e8-9b39-9a4b3e906a68.png)
Change the first sentence to include the words "in Indonesia":
... takes into account the population and cities in Indonesia affected by different levels ...
Change the second sentence to refer to the estimated 2015 world pop data : 
... derived by DMInnovation from WorldPop 2015 estimated population data and BPS 2010 census data, place ...
Change the second last sentence to say:
... no fatalities occur for shake levels less than MMI IV.
Delete the statement: Fatality counts of less than 50 are rounded down.

**In the volcanic ash report disclaimer:**
![image](https://user-images.githubusercontent.com/5743135/39412900-3d0e5ab8-4c66-11e8-9db0-4f155922e17a.png)
Change the first sentence to include the words "in Indonesia":
... population, cities and landcover in Indonesia affected ...
Change the third sentence to refer to the estimated 2015 world pop data : 
... derived by DMInnovation from WorldPop 2015 estimated population data, place information

No changes are required for the flood report template in Jakarta as it already mentions the analysis extent and uses different population data.

@ivanbusthomi  - please implement this and the relevant translations

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan - The changes to the disclaimer text have been pushed to the template repository. Closing this ticket. Thanks
