### ISSUE TITLE
Realtime 4 about pages updates

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#217]
we need to update the about pages to reflect changes to the exposure data.

I have made the following edits to the English page for earthquake - this is the new text for the final paragraph.
The InaSAFE Realtime Earthquake report shows details of the earthquake event such as the magnitude, date, time, location and depth with the results of the InaSAFE Realtime Earthquake analysis. The InaSAFE Realtime Earthquake analysis estimates the number of people **in Indonesia** exposed by each MMI level using **a modelled estimate of 2015 population** exposure data from World Pop. The analysis report also lists nearby places (district capitals) based on place names from Badan Informasi Geospasial (BIG) with an estimate of the urban population using Badan Pusat Statistik (BPS) 2010 population census data. InaSAFE Realtime Earthquake uses a distance and direction algorithm to identify the closest populated place. InaSAFE Realtime Earthquake analysis uses the ITB bayesian fatality model to estimate the number of fatalities for each earthquake event. The fatality calculation assumes that no fatalities occur for shake **levels less than MMI IV.**

@ivanbusthomi  - please update the translated version to match this final paragraph. Bold is to show you the changes :)

----------------------------------
Please update the translated Volcanic Ash about page to reflect the changes in the English version in this paragraph. 
The InaSAFE Realtime Ash analysis report estimates the number of people **in Indonesia exposed** to each ash fallout class based on the thickness of ash on the ground; using a **modelled estimate of 2015 population exposure data** from World Pop. People are considered **to be exposed** if they are within the area of the event. The InaSAFE Realtime Volcanic Ash analysis also estimates the area of land cover affected, and lists nearby places and airports in the affected area by fallout level. 
@ivanbusthomi  Changes are marked in bold and reflect the extent of the analysis, the new worldpop data and the change to people exposed not people affected.

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan - I've made the changes to the about pages in the staging environment. Closing this ticket, thanks
