### ISSUE TITLE
realtime not updating the recent earthquake

### ISSUE THREAD

**Issue by husnimubarok** [inasafe/inasafe-realtime#224]
realtime.inasafe.org is not updating the impact analysis of the recent earthquake event. the page is four days behind.

![realtime inasafe 23092019](https://user-images.githubusercontent.com/860363/65421757-bbac3d80-de2e-11e9-8852-d864b1951694.jpg)

**Comment by lucernae** [comment]
Thanks for reporting this mas @husnimubarok . I will look on it.

**Comment by lucernae** [comment]
Not receiving shakemaps due to insufficient spaces (backups filling up).
We need to use better backup mechanism.

**Comment by lucernae** [comment]
Problem has been fixed short term for now. We reduce backup frequency.
I will close this.
