### ISSUE TITLE
Earthquake analysis

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#25]
problem

We need to ensure that legacy details are retained in the migration of InaSAFE3.5.3 earthquake analysis to the new version 4 architecture.
See original ticket at https://github.com/inasafe/inasafe/issues/3654 for further discussion.

**Comment by Charlotte-Morgan** [comment]
adding to this - we need to retain legacy of changes to the way we report fatalities - ie when did we stop rounding down less than 50. when did we change default IF. This is important if someone reruns an old report with new analysis settings

I think this ticket belongs in InaSAFE not realtime

**Comment by ismailsunni** [comment]
Yes, I agree, this is for InaSAFE. I will create new ticket in InaSAFE, reference to this, and close this ticket.
Thanks @Charlotte-Morgan
