### ISSUE TITLE
Improve celery monitoring

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#33]
We have to know somehow when celery task stopped or hanging
Alternatively, make a periodic celery task refresh using cron
Try use flower for celery monitoring

See original ticket at https://github.com/inasafe/inasafe/issues/3697 for further discussion.

**Comment by lucernae** [comment]
From the experience with GeoSAFE.
We might also want to try scaling in addition with cronjob to make a weekly task refresh.

**Comment by gubuntu** [comment]
moving to backlog since this should be addressed as part of the seamless platform convergence

**Comment by Charlotte-Morgan** [comment]
![image](https://user-images.githubusercontent.com/5743135/34507372-7807db5a-f089-11e7-8aec-9c92f255d183.png)

**Comment by lucernae** [comment]
Celery now regularly refreshed using crontab scheduler from Rancher. So, in case it gets down, it will brought up again.
