### ISSUE TITLE
downloads and icons

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#35]
- Enable downloading derived product (contours, flood hazard, etc)
- Ensure download icons and tooltips on flood and eq are consistent (change flood & volcano to match eq page)
- Missing hazard download tool in flood
- Translate realtime flood to Indonesian

See original ticket at https://github.com/inasafe/inasafe/issues/3701 for further discussion.

**Comment by timlinux** [comment]
> Enable downloading derived product (contours, flood hazard, etc)

Is this really done @lucernae ? I still can't get the other derived products for EQ:

![screen shot 2017-02-18 at 10 45 15 pm](https://cloud.githubusercontent.com/assets/178003/23096764/1860c8ea-f62c-11e6-9449-c897be86b5ce.png)

**Comment by gubuntu** [comment]
yip, still the case

**Comment by gubuntu** [comment]
Please test and close @ivanbusthomi

**Comment by ivanbusthomi** [comment]
I can confirm that this is fixed. closing this
