### ISSUE TITLE
Realtime earthquake translation in Bahasa Indonesia

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#36]
Problem

Similar issue with InaSAFE Realtime flood translation (#3291), currently InaSAFE Realtime Earthquake in Bahasa Indonesia is not 100% translated yet.

See original ticket at https://github.com/inasafe/inasafe/issues/3714 for further discussion.

**Comment by lucernae** [comment]
linked with #50

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe-django#190
