### ISSUE TITLE
We need a working, documented backup system for the server

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#37]
Can you please spend some time to come up with a plan to ensure we have a proper backup system? Perhaps we can rsync / btsync backups to a filestore on the AIFDR cluster? Also we should document how to go about restoring the running services in the case of total hardware failure / security breach. Including but not limited to:

-     osm.linfiniti.com (for osm downloader) - @timlinux to do
-     experimental.inasafe.org (for nightly packages)
-     test documentation builds
-     live web site
-     download site
-     blog

We can also look at using hetzner backup services though I don't think they provide a big enough storage space. Also we could look at using backblaze - its USD 5 a month with unlimited storage.

@Charlotte-Morgan 
See original ticket at https://github.com/inasafe/inasafe/issues/1298 for further discussion.

**Comment by gubuntu** [comment]
@lucernae the backups are working so we just need the documentation?

**Comment by gubuntu** [comment]
This issue was moved to inasafe/docker-realtime-orchestration#72

**Comment by gubuntu** [comment]
This issue was moved to inasafe/docker-realtime-orchestration#74
