### ISSUE TITLE
Make sure shakemaps are pushed from BMKG

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#38]
this is a follow up issues of #2014 https://github.com/inasafe/inasafe/issues/2014.

We need to make sure all the shakemaps pushed is working and compatible with InaSAFE EQ Realtime

See original ticket at https://github.com/inasafe/inasafe/issues/2058 for further discussion.

**Comment by Charlotte-Morgan** [comment]
@lucernae to talk to @hadighasemi

**Comment by lucernae** [comment]
I think we can close this.
