### ISSUE TITLE
We need a way to test that Realtime is running

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#39]
Problem

It is possible for InaSAFE Realtime to stop working and for no one to notice.
Today - the last Realtime event is dated 13th July, yet there have been 17 earthquakes in Indonesia since that date, 5 of which are greater than 5.0
We seem to be unaware of system failures unless a person looks at it.
InAWARE provides links to files that do not exist.
proposed solution

We need to build an automatic system to check that EQ realtime is running and generating reports regularly. This system needs to run automatically and send a message to an administrator or trigger a server restart if there is an error.
I propose a daily / 12 hourly test where a dummy shakemap is sent to realtime. This dummy data is tagged in a way so that the resulting impact assessment is filtered off and stored in a test location (not delivered to the real output).
If a new file is not delivered to the test location at the expected time - a message is sent to an administrator to check the system / the server is poked to make it run ...

See original ticket at https://github.com/inasafe/inasafe/issues/2160 for further discussion.

**Comment by gubuntu** [comment]
Rancher and sentry monitoring to be implemented shortly

**Comment by gubuntu** [comment]
a case in point is bnpb realtime which is frequently down

**Comment by lucernae** [comment]
Health check integrated in Rancher.
