### ISSUE TITLE
Realtime site needs to advise user to allow popups

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#44]
Problem

On some browsers e.g. chrome, downloading the realtime reports does not work because the browser blocks popups.

I think it would be good (I know this is ironic) to see if the user has popups blocked and make a modal popup informing them that they should unblock popups. Alternatively, we could use an approach like we have on WebSafe where the result is displayed in a modal->iframe...

See original ticket at https://github.com/inasafe/inasafe/issues/2937 for further discussion.

**Comment by Charlotte-Morgan** [comment]
@lucernae  - please delegate this if you can :)

**Comment by myarjunar** [comment]
Hi @Charlotte-Morgan , for this issue, we could either open the pdf on the same tab (overlaying the pdf on the web content) or create our own warning for the user to enable popup on the browser.  Which one is better for you ?

**Comment by Charlotte-Morgan** [comment]
@myarjunar - my preference would be a nice user warning to enable the popup

**Comment by gubuntu** [comment]
@myarjunar what is the status of this?

**Comment by lucernae** [comment]
Uh, it hasn't been implemented I think.
