### ISSUE TITLE
Flood Realtime: Jakarta boundary error

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#49]
# problem

there is an an error with the boundary of the Jakarta province shown on the maps.
Only the outline should be a bold line. Not the extra line as shown here:

![image](https://cloud.githubusercontent.com/assets/5743135/19100996/1ddaa222-8aee-11e6-9186-c4bdd0d43a75.png)

@ivanbusthomi - can you please check the error is not in the synced data. if it is, fix and update the synced data - thanks

**Comment by lucernae** [comment]
I will send the file later

**Comment by lucernae** [comment]
From @ivanbusthomi :
[03-Aggregation-Data.zip](https://github.com/inasafe/inasafe-realtime/files/874266/03-Aggregation-Data.zip)

**Comment by gubuntu** [comment]
sounds like this can be closed then?

**Comment by lucernae** [comment]
![screenshot_20170407_140706](https://cloud.githubusercontent.com/assets/831865/24789111/8f0a4c2a-1b9b-11e7-8422-a10985ff3cf9.png)

**Comment by lucernae** [comment]
Close this.
