### ISSUE TITLE
Please btsync share shakemaps-extracted for realtime

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#51]
Problem
Data Sync

We currently sync the grid inputs but I would like to have a synced folder of the

    PDF reports generated (I thought we already have a btsync share for this)
    the shakemaps-extracted folder - so that we can also have the derivative products.

Currently if someone asks for the extracted products we dont have a smooth way to provide them and also if we spin up a new server instance, it would be good to restore the historical outputs seamlessly.

Note that currently shakemaps-extracted is 47GB so people syncing it should be aware of that.

timlinux@inasafe-docker:/home/data/docker-realtime-orchestration⟫ du -sh shakemaps-extracted/
47G     shakemaps-extracted/

Data access by web front end

Additionally I would also like to see a download link on the realtime site that will let you download the derivative products on an event by event basis.
Expected Behaviour

    We should have a shared RO key for anyone who wants to subscribe to these products
    The RW key should be part of the server config and used only by production server(s)

See original ticket at https://github.com/inasafe/inasafe/issues/3492 for further discussion.

**Comment by gubuntu** [comment]
include Kartoza Jhb office NAS as a sync target
