### ISSUE TITLE
Flood table heading should be clearer

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-realtime#61]
![screen shot 2017-02-10 at 9 05 51 am](https://cloud.githubusercontent.com/assets/178003/22817490/46341ad2-ef70-11e6-9557-862bbb1f3b7f.png)

"RW Flooded" should rather be "# Flooded RWs"

**Comment by Charlotte-Morgan** [comment]
@myarjunar  - is this something you can tweak?

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe-django#213
