### ISSUE TITLE
handle both shakemap versions

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-realtime#64]
initial and post-processed (data-informed) shakemaps will be sent correctly (with distinct filenames) late Feb 2017

We need to receive and ingest both and handle them both in reporting

**Comment by gubuntu** [comment]
from conversation with Pak Yedi from BMKG:

'initial' and 'post-processed' are the best terms. 

Pak Yedi's 'earthquake and tsunami' department produces the 'raw' (modelled) shakemaps immediately (first five minutes) after an event. They get a timestamp-based id and all shakemaps that are MMI >= 5  OR felt = true get pushed to InaSAFE and BNPB. 

Pak Hartadi's department (earthquake engineering) generates shakemaps from scratch completely separately, based on accelerometer data, using different software on different computers.  These normally come through after the 'raw' shakemaps and are completely unrelated (other than describing the same event) and will most likely have a different id for the same event. 

We (InaSAFE) should analyse both in the absence of specific instructions from BNPB and flag the results as clear alternatives for the same event.  

Each type gets written to separate directories (Hartadi's to 'corrected'?) and that is the way we should distinguish them...

**Comment by Charlotte-Morgan** [comment]
@hadighasemi  - grateful if you can confirm that this meets with your understanding and approval for the handing of realtime earthquake data from BMKG

**Comment by Charlotte-Morgan** [comment]
hi @hadighasemi  could you please provide advise on this.
My understanding is that at GA we refer to original (the raw data) and data-informed (the subsequent shake with observed data).
@lucernae  - are you currently receiving and processing both shake maps?

cc @RikkiWeber @ivanbusthomi

**Comment by hadighasemi** [comment]
I am not sure about GA's terminology as we do not have ShakeMap products! But I agree that "'initial' and 'post-processed' are the best terms." :)

**Comment by ivanbusthomi** [comment]
Hi @lucernae @gubuntu and @Charlotte-Morgan 
this is some mock up that I create based on our discussion in the realtime meeting. It is like an additional button to open the report from the ~data-informed~ _post-processed_ shakemaps.
![image](https://files.gitter.im/ivanbusthomi/VG1v/image.png)

**Comment by Charlotte-Morgan** [comment]
Thanks @ivanbusthomi for the mock up. 
In my mind the Action column will have space for 4 icons in every row of the table.
The only rows with 2 active report icons will be records where there is an initial and post processed shakemap.
My preference will be for the download icons to all be aligned. this means that for records where there is no post processed shake map, there will be either a space or greyed out inactive second report icon

**Comment by lucernae** [comment]
Hi! @Charlotte-Morgan @ivanbusthomi @gubuntu Finally a UI update from my side.
This is the new icons colletions in the table: (can be seen and tested in testing.realtime.inasafe.org)

<img width="1023" alt="screen shot 2018-03-16 at 14 32 58" src="https://user-images.githubusercontent.com/831865/37508746-02fc4de2-2927-11e8-9c1c-b21b31d81402.png">

<img width="337" alt="screen shot 2018-03-16 at 15 50 26" src="https://user-images.githubusercontent.com/831865/37511542-c830055e-2931-11e8-82d5-81ca417c4ad3.png">


Some input and feedback from my side:
- I think I need some help to get a nice distinct icon for the second report at the middle. Right now, I used the same icon.
- The product list will be displayed in download icons. If it doesn't exists, it will not be in the list.
- The icons behave the same way in the marker popup

Feel free to coment for additional change request for the UI.

**Comment by lucernae** [comment]
Mechanism is in place, but at the moment we lost connection to the corrected shakemap
