### ISSUE TITLE
Flood: Error in min needs calc

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#65]
### problem ###
Flood realtime minimum needs are being calculated for the 'affected' population not the displaced population.

### proposed solution ###
Minimum needs should be calculated for the estimated displaced population- ie the 1% of exposed people.

in this example: 
![image](https://cloud.githubusercontent.com/assets/5743135/23099686/857dec32-f69f-11e6-916c-f73334e4117e.png)

we would expect to offer 18 toilets (1 per 20 displaced people) not 1800 for the 350 people :)

@felix-yew @ivanbusthomi @samnawi @gubuntu

**Comment by lucernae** [comment]
Calculate Minimum needs from IDP.
<img width="950" alt="screen shot 2017-02-21 at 13 39 50" src="https://cloud.githubusercontent.com/assets/831865/23153458/547eab88-f83b-11e6-8851-6538bfee3d5c.png">

**Comment by Charlotte-Morgan** [comment]
that looks much more sensible :)

**Comment by gubuntu** [comment]
LGTM, you can close
