### ISSUE TITLE
We need to update a description of InaSAFE Flood Realtime

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe-realtime#66]
# Problem
We need to update a description of InaSAFE Flood Realtime. 
1. Now, in the description still mention the PetaJakarta.org as the flood data source, but in the fact, **PetaJakarta.org** has been replaced by **PetaBencana.id**. 
2. Update the media that send a flood event to use the crowdsourcing data, like twitter, telegram, qlue, detik, and Z-Alert.

# Expected behaviour
Change the PetaJakarta.org to PetaBencana.id in the description and then update the media to send the flood event.
![image](https://cloud.githubusercontent.com/assets/13621886/23114060/34d37cfe-f76f-11e6-8322-9cb5b85c97f6.png)

# Proposed solution
The description has the correction data source and the media to send a report of a flood event.

Cc:
@gubuntu @Charlotte-Morgan @timlinux @samnawi @fredychandra @ivanbusthomi

**Comment by Gustry** [comment]
See : https://github.com/inasafe/inasafe-realtime/issues/23

**Comment by felix-yew** [comment]
Yes, @Gustry but it also changes the crowdsource data reporting, as explain in the information (in report icon) PetaBencana.id website.

**Comment by Charlotte-Morgan** [comment]
We also need to include a statement about the frequency of the analysis and the method as per gitter chat.

**Comment by lucernae** [comment]
@felix-yew @Charlotte-Morgan @ivanbusthomi 

Please check my wording before I deployed it.

![screenshot_20170411_175706](https://cloud.githubusercontent.com/assets/831865/24906021/5242b122-1ee0-11e7-8c8d-b1896cc8146c.png)

**Comment by timlinux** [comment]
@lucernae maybe easier for us to edit if you paste as text too.

Report is then -> A report is then
last 6 hours interval -> last 6 hour interval
if there is any -> if there was any flooding in that period
deepest water -> deepest water depth recorded
6 hours interval -> 6 hour interval
respond faster -> respond more quickly

**Comment by gubuntu** [comment]
also:
floods in the Jakarta -> floods in Jakarta
crowd sourcing -> crowdsourced
report will include -> report includes
will show -> shows

**Comment by felix-yew** [comment]
hi, mas @lucernae - I think input from @timlinux and @gubuntu can improve the description so it is easy to read and understand :+1:

**Comment by Charlotte-Morgan** [comment]
it should be 'BPDB-DKI Jakarta' not 'DPDB-DKI'

**Comment by Charlotte-Morgan** [comment]
@gubuntu  actually - I am not sure this includes the data from BPBD DKI validation. Please check email from Mathew Berryman in response to request for metadata.  BPBD DKI web site shows different maps to what we do at the same time. Our maps are the same as BNPB InAWARE data

**Comment by Charlotte-Morgan** [comment]
@rizky - I think it would be good to use the intro paragraph in the about page as the same text for the landing page. I can not see staging now, so i am guessing its the intro paragraph that is relevant.

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe-django#189
