### ISSUE TITLE
Notes from PVMBG meetings

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#69]
Ash Realtime:

- Change disclaimer
- add notes above sea level on the form field
- add fields duration forecasts
- add in the reports a notes: what the time is and the duration
- add KRB/evacuation route info to the map
- auto conversion from netCDF to GeoTiff?
- swap district and province name in the autocomplete volcano name
- perhaps eruption height can be taken from netCDF
- thresholds in ash might be the same for landcover and population, but the action checklist might be different

**Comment by ivanbusthomi** [comment]
> add KRB/evacuation route info to the map

I just want to clarify some updates from our partner in PVMBG. They've changed their request and only want to show the evacuation routes, not the KRB data.

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi  - can you please confirm which items from the list above have been done and what is outstanding.  I can then decide if anything else will be done now or after we migrate to version 4. 
ie adding evacuation routes can be after we migrate.
Some of these items - ie action checklists need to be written up as tickets for InaSAFE not realtime.

cc @RikkiWeber @estukriswati

**Comment by gubuntu** [comment]
@ivanbusthomi please review these (and make them tickboxes in the OP and tick off what's done and add references to sub-issue numbers)
