### ISSUE TITLE
[Realtime] Location / Placenames for EQ realtime

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#7]
This afternoon, I've a quickchat with Ibu Dian from Pusdatinmas BNPB.
This is the conclution for our conversation :

    For location of epicentrum
    She gives the suggestion to use the information accordingly with BMKG.
    Maybe we can extract the information from this link http://data.bmkg.go.id/gempaterkini.xml
    image
    For the nearby location
    They (as a user) usually want to know the popular city like the capital of district.
    Placenames with population data
    They don't have any data of this.
    As the discussion with @Charlotte-Morgan. I'll try to use the capital of district in our database, and calculate the population in that town based on the percentage of population in rural and urban based on the data from BPS (population census 2010). Then try to compare it with the actual data or with the data from the other agency (if they have).

Thank you.
CC

@timlinux @lucernae @fredychandra 

See original ticket at https://github.com/inasafe/inasafe/issues/2589 for further discussion.

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - lets discuss this with BNPB when we meet on 28th

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi and @samnawi  please follow up with BNPB

**Comment by Charlotte-Morgan** [comment]
@samnawi  - is this finished and the result is the places data we use now?

**Comment by ivanbusthomi** [comment]
I think this is already done
