### ISSUE TITLE
add Google analytics to realtime

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-realtime#72]

**Comment by gubuntu** [comment]
discuss with @gubuntu which account to use...one of Kartoza's

**Comment by gubuntu** [comment]
Gavin to generate code

**Comment by gubuntu** [comment]
paste this into base template
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-93181136-1', 'auto');
  ga('send', 'pageview');

</script>
```

I have created an InaSAFE Analytics account under Kartoza with the realtime website as its first 'property'. We can add other websites (geonode etc.). Kartoza staff can see the admin page at https://analytics.google.com/analytics/web/#management/Settings/a93181136w137865347p142148048/%3Fm.page%3DTrackingCode/

**Comment by lucernae** [comment]
Implemented.
