### ISSUE TITLE
establish links between flood realtime and InAWARE

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-realtime#76]
(now or not going to happen)

@timlinux please expand

**Comment by timlinux** [comment]
We need:

* To make contact with one of the PDC folks to agree on how we reference flood events in a common way
* Either set up a push to PDC (assuming we can generate the same flood event ids) or ask them to set up a pull from realtime (using common id or by fetching based on time slice). We have done both these approaches before so Rizky should know the ropes there. Push to PDC is preferable.

@lucernae knows the technical folks to talk to  so I think just jump into an email conversation with them but be sure to loop DMI in before actually implementing anything.

**Comment by lucernae** [comment]
Not possible
