### ISSUE TITLE
Small improvement for Realtime Earthquake pdf report

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#79]
Currently, we already have an informative pdf report generated from the InaSAFE Realtime Earthquake platform. To make the report better, we need to update a few parts in the pdf report in terms of terminologies that are used, data source information and some table element.
___
Here are some suggestions, hopefully it can easily be updated.

* Update the term `affected` to `exposed`
![image](https://cloud.githubusercontent.com/assets/7351977/23785551/d6cbc6ae-059a-11e7-8162-bb3e85e855bc.png)

* The MMI number in the table should be centered, and the column size should be equal.
![image](https://cloud.githubusercontent.com/assets/7351977/23785637/4d225a8e-059b-11e7-90ba-60e6986f0bb5.png)

* Update the disclaimer text at the bottom of the page to match the update in the data that are used.
![image](https://cloud.githubusercontent.com/assets/7351977/23785700/90cb53c6-059b-11e7-9819-831ab69a7de8.png)
This is the updated text:

_This impact estimation is automatically generated and only takes into account the population and cities affected by different levels of ground shaking. The estimate is based on ground shaking data from BMKG, population count data derived by DMInnovation from worldpop.org.uk, place information data provided by Indonesian Geospatial Portal at http://portal.ina-sdi.or.id and software developed by BNPB. Limitations in the estimates of ground shaking, population and place names datasets may result in significant misrepresentation of the on-the-ground situation in the figures shown here. Consequently, decisions should not be made solely on the information presented here and should always be verified by ground truthing and other reliable information sources. The fatality calculation assumes that no fatalities occur for shake levels below MMI 4. Fatality counts of less than 50 are rounded down._

___
**CC** @Charlotte-Morgan @timlinux @gubuntu @lucernae

**Comment by ivanbusthomi** [comment]
Mas @lucernae , could you please remind us what this number tells us?
![image](https://cloud.githubusercontent.com/assets/7351977/24039597/626175f4-0b38-11e7-9063-858f817a0b03.png)

**Comment by lucernae** [comment]
That's the timezone being used in the report.

**Comment by lucernae** [comment]
I also realign the numbers and shaking description. Just to follow the header.
![screenshot_20170411_110505](https://cloud.githubusercontent.com/assets/831865/24892429/c61fc6dc-1ea6-11e7-90ad-613ce5da6e5e.png)

**Comment by gubuntu** [comment]
People exposed and perceived shaking are now right-justified. All three rows should be centre-justified.

**Comment by lucernae** [comment]
Actually I did the right-justified because it looks nice. It feels strange for the number to be centre-justified.

**Comment by lucernae** [comment]
do it center - aligned for all

**Comment by samnawi** [comment]
> ..................., place information data provided by Indonesian Geospatial Portal at **http://portal.ina-sdi.or.id** and software developed by BNPB................

I proposed to update the url address on above :
..................., place information data provided by Indonesian Geospatial Portal at **http://tanahair.indonesia.go.id** and software developed by BNPB................

**Comment by ivanbusthomi** [comment]
Closing this since the change suggestions have already been implemented.
