### ISSUE TITLE
Realtime EQ contour smoothing

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#8]
problem

InaSAFE EQ realtime needs to have its contours smoothed for display. However, the number of people exposed to different shaking levels should be estimated from the raw (not smoothed) data.

proposed solution

For smoothing, Hadi used spatial convolution of intensity matrix with a smoothing kernel to filter out the high frequency part of the contours. In MATLAB you can do this by using “conv2” function.

See original ticket at https://github.com/inasafe/inasafe/issues/2662 for further discussion.

**Comment by Charlotte-Morgan** [comment]
@hadighasemi - will be in Jakarta soon and plans to work on this while he is here.

**Comment by Charlotte-Morgan** [comment]
@lucernae  - can you please provide update on this

**Comment by Charlotte-Morgan** [comment]
@hadighasemi - can you please review smoothing. Does it look right to you?  @lucernae says it has been implemented
cc @RikkiWeber

**Comment by lucernae** [comment]
Coming back to this issue. 
Perhaps it is better if I made some comparison.
The smoothing works by applying gaussian filter and is parameterized by sigma factor.
Default value chosen at 0.9 based on previous discussion between Hadi and I in Jakarta.

Using sigma factor = 0 (Original contour without smoothing)
<img width="470" alt="screen shot 2017-05-09 at 15 06 52" src="https://cloud.githubusercontent.com/assets/831865/25841148/2eb7ca7c-34c9-11e7-9b76-b1cb7442f17a.png">

Using sigma factor = 0.9 (We currently use this at the moment)
<img width="468" alt="screen shot 2017-05-09 at 15 07 45" src="https://cloud.githubusercontent.com/assets/831865/25841169/49f728e6-34c9-11e7-9ee9-751923c6c347.png">

If it's not smooth enough, we can increase the factor

Using sigma factor = 2
<img width="478" alt="screen shot 2017-05-09 at 15 09 33" src="https://cloud.githubusercontent.com/assets/831865/25841242/8d310ea6-34c9-11e7-9fe9-7ef2663b2650.png">

Using sigma factor = 10 (looks really deformed, perhaps this is the borderline of not good.)
<img width="476" alt="screen shot 2017-05-09 at 15 11 11" src="https://cloud.githubusercontent.com/assets/831865/25841307/c4a45316-34c9-11e7-8c6e-4facd1c62ac5.png">

**Comment by gubuntu** [comment]
LGTM, I'm happy to close.

We should add this to QGIS Core!
