### ISSUE TITLE
Realtime Volcanic Ash to use data from Ash3D modelling.

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe-realtime#80]
Our partner from PVMBG has requested that for the current version they want to use the Ash3D modelling as an input for Volcanic Ash Realtime. They suggest that we download the data from https://vsc-ash.wr.usgs.gov/public/public.php
The one that is generated by PVMBG created by user `estukriswati` . If it can works, they are happy to release it for the current version.
___
**CC** @RikkiWeber @Charlotte-Morgan @gubuntu @lucernae @estukriswati

**Comment by Charlotte-Morgan** [comment]
thanks @ivanbusthomi 
I note that the classification in the Ash3D is not the same as the impact report requested for realtime. I think we have some more work to do to join the dots here.
@RikkiWeber - do you have any advice on this?

**Comment by Charlotte-Morgan** [comment]
@RikkiWeber  - please talk to me on this to provide advice on what is required:
can we get polygons
can we get machines to talk to each other
can we use the intervals in the data
is 'raw' data available for us to classify

**Comment by RikkiWeber** [comment]
@Charlotte-Morgan @ivanbusthomi - At the moment I am not sure. I am trying to get an account on Ash3D so I can make some synthetic data to look at. I will get back to you.

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan and @RikkiWeber,
This is some Ash3D data that I received from Ibu @estukriswati from our last visit. Apparently, we need an account to download the actual data that can be used in processing.

[ash3d_sin20170317_1153_dep_20170317-05-00-40z.zip](https://github.com/inasafe/inasafe-realtime/files/874678/ash3d_sin20170317_1153_dep_20170317-05-00-40z.zip)
[ash3d_sin20170307_0242_dep_20170307-05-21-00z.zip](https://github.com/inasafe/inasafe-realtime/files/874679/ash3d_sin20170307_0242_dep_20170307-05-21-00z.zip)

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - please update with the latest data from @RikkiWeber

**Comment by ivanbusthomi** [comment]
**Update**
Data from @RikkiWeber:
[ash3d_trial-guntur_dep_20170412-02-07-06z.zip](https://github.com/inasafe/inasafe-realtime/files/975164/ash3d_trial-guntur_dep_20170412-02-07-06z.zip)

> can we get machines to talk to each other

This last two weeks, there has been a migration process in the realtime server,  hopefully after the process is finished, mas @lucernae can start working on this. Could you shed us some light mas @lucernae ? :smile:

**Comment by ivanbusthomi** [comment]
Closing this now as we agreed to use the Fall3D data for the Volcanic Ash Realtime.
