### ISSUE TITLE
clarify shakemap terminology

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-realtime#81]
# Problem
There are a few terms in use that refer to shakemap processing levels. We need to be clear about what these are so we all have a common understanding

Are these correct?
1. 'Raw' shakemap. Estimate. Sent immediately.
1. 'Data-infomed' (also incorrectly called 'corrected'). Sent a few minutes later along with ground station data.
1. 'Strong-motion' shakemap. Is this any different to the first two?

**Comment by hadighasemi** [comment]
Here are the definitions:

ShakeMap: A map representing the level of earthquake ground shaking in terms of MMI (intensity), PGA (peak ground acceleration), SA (spectral acceleration), etc.

**1. 'Raw' shakemap. Estimate. Sent immediately.**
in this version, the level of earthquake ground shaking is estimated by only using empirical equations.

**2. 'Data-informed' (also incorrectly called 'corrected'). Sent a few minutes later along with ground station data.**
in this version, the  level of earthquake ground shaking is estimated by combining the predictions from empirical equations with those calculated directly from recorded data (observation) at seismic stations.

**3. 'Strong-motion' shakemap. Is this any different to the first two?**
this would be same as "2. Data-informed"

Please let me know if further explanation required.

**Comment by gubuntu** [comment]
Thank you @hadighasemi 

Please note @lucernae
