### ISSUE TITLE
Feedback from Hazard Agencies

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#82]
# PVMBG (Ash Realtime)

## Feature enhancement

- Change disclaimer text
- Add notes (above sea level/a. s. l) on the form field
- Add fields duration forecasts
- Possibility of using shapefile for hazard
- Add in the report a notes that what the time is about and the duration
- Add KRB information to the map
- Conversion from netCDF to geo tiff?
- Swap district and province name
- Eruption height mungkin bisa diambil dari netCDF
- Thresholds in Ash might be the same for landcover and population but the action checklist might be different for different classes
- Hide ash until automated forecast modelling (Ash3D)

# BMKG (Earthquake Realtime)

## Notes

- Shakemap MMI < 5 only for felt earthquake. Shakemap MMI > 5 will always be sent.
- They use Nagios to check BNPB server and/or Realtime
- BNPB sync still not working
- They have a website division that possibly have some sort of API to check the list of felt shakemap (we currently use scrapper)
- Shakemap from strong motion processing (corrected) has different Shake ID, we need to find out how to link this with particular Shake ID that actually happens.

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi - can you please review this list and turn it into separate tickets for different products. Maybe notes should be copied to Asana or a realtime meeting notes record if they do not need action here

**Comment by gubuntu** [comment]
@ivanbusthomi please review these (and make them tickboxes in the OP and tick off what's done and add references to sub-issue numbers)
