### ISSUE TITLE
a Problem With "Select Area" Tool

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe-realtime#86]
I got a problem after using "Select Area" Tool on Earthquake Realtime.
After I click "remove selection", I can't drag the map to the other particular area.
![realtime2](https://cloud.githubusercontent.com/assets/8871958/25173030/f749b264-251c-11e7-9a58-089d305692c6.gif)

Browser : Chrome

cc : @lucernae @ivanbusthomi

**Comment by Charlotte-Morgan** [comment]
hi @lucernae  - this might be good to fix before the training

**Comment by gubuntu** [comment]
@lucernae, I also get the following:
1. Select Area always zooms out to multiple earths even if I have manually zoomed in before. Why does it autozoom at all? I'd expect it to let you digitise an area independent of zoom level. 
1. 'Select area within current zoom' seems to just zoom in to one random event and show its popup.

I'm not sure if the select area tool is useful in its current state. Was its original intention to spatially filter events?

If it's not a quick fix consider disabling it for the training?

**Comment by gubuntu** [comment]
- [ ] fix and bring back the select area tool now that September training is over
- [ ] add a toggle for an auto view extent filter

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe#4473

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe-django#198
