### ISSUE TITLE
Shakes coming from the future

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#87]
We had shakes with timestamp in the future:

[20170429033724-en.pdf](https://github.com/inasafe/inasafe-realtime/files/975424/20170429033724-en.pdf)

<img width="1180" alt="screen shot 2017-05-04 at 14 32 35" src="https://cloud.githubusercontent.com/assets/831865/25694013/8f962236-30d6-11e7-8141-9c85919e843f.png">

We will delete this event for now.

CC: @ivanbusthomi is currently asking BMKG about this.

**Comment by lucernae** [comment]
> And, is there any way for us to notice if in the future there is an event with an incorrect timestamp like this, but the timestamp for that event is in the past?

No. We have to put additional code. It's not that hard to implement this, but we have to specify how to present this information (do we display or ignore it) and what action we should take (notify admin? create crash email report?)

**Comment by ivanbusthomi** [comment]
Just want to give an update from pak Sigit that there will never be an event for the future. This case is usually for the test event, and can always be ignored.

**Comment by gubuntu** [comment]
manually delete future test shakemaps (though Django admin) if they ever appear again
